# yaml-language-server: $schema=https://flagd.dev/schema/v0/flags.json
flags:
  app-general:
    state: ENABLED
    variants:
      "on": true
      "off": false
    defaultVariant: "off"
  app-container:
    state: ENABLED
    variants:
      "on": true
      "off": false
    defaultVariant: "off"
  app-helm-chart:
    state: ENABLED
    variants:
      "on": true
      "off": false
    defaultVariant: "off"
