// Code generated by "stringer -type=WarpOperationType -output=warp_operation_type_string.go -linecomment=true"; DO NOT EDIT.

package bist

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WarpOperationTypeGet-0]
	_ = x[WarpOperationTypePut-1]
	_ = x[WarpOperationTypeDelete-2]
	_ = x[WarpOperationTypeList-3]
	_ = x[WarpOperationTypeStat-4]
	_ = x[WarpOperationTypeMixed-5]
}

const _WarpOperationType_name = "getputdeleteliststatmixed"

var _WarpOperationType_index = [...]uint8{0, 3, 6, 12, 16, 20, 25}

func (i WarpOperationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WarpOperationType_index)-1 {
		return "WarpOperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WarpOperationType_name[_WarpOperationType_index[idx]:_WarpOperationType_index[idx+1]]
}
