// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/essential/v1/essential.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Essential_Type int32

const (
	Essential_UNSPECIFIED Essential_Type = 0
	Essential_KUBERNETES  Essential_Type = 1
	Essential_CEPH        Essential_Type = 2
)

// Enum value maps for Essential_Type.
var (
	Essential_Type_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "KUBERNETES",
		2: "CEPH",
	}
	Essential_Type_value = map[string]int32{
		"UNSPECIFIED": 0,
		"KUBERNETES":  1,
		"CEPH":        2,
	}
)

func (x Essential_Type) Enum() *Essential_Type {
	p := new(Essential_Type)
	*p = x
	return p
}

func (x Essential_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Essential_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_essential_v1_essential_proto_enumTypes[0].Descriptor()
}

func (Essential_Type) Type() protoreflect.EnumType {
	return &file_api_essential_v1_essential_proto_enumTypes[0]
}

func (x Essential_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Status_Level int32

const (
	Status_INFO     Status_Level = 0
	Status_LOW      Status_Level = 1
	Status_MEDIUM   Status_Level = 2
	Status_HIGH     Status_Level = 3
	Status_CRITICAL Status_Level = 4
)

// Enum value maps for Status_Level.
var (
	Status_Level_name = map[int32]string{
		0: "INFO",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	Status_Level_value = map[string]int32{
		"INFO":     0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x Status_Level) Enum() *Status_Level {
	p := new(Status_Level)
	*p = x
	return p
}

func (x Status_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_api_essential_v1_essential_proto_enumTypes[1].Descriptor()
}

func (Status_Level) Type() protoreflect.EnumType {
	return &file_api_essential_v1_essential_proto_enumTypes[1]
}

func (x Status_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Essential struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        Essential_Type         `protobuf:"varint,1,opt,name=type,enum=otterscale.essential.v1.Essential_Type"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_ScopeUuid   *string                `protobuf:"bytes,11,opt,name=scope_uuid,json=scopeUuid"`
	xxx_hidden_ScopeName   *string                `protobuf:"bytes,12,opt,name=scope_name,json=scopeName"`
	xxx_hidden_Units       *[]*Essential_Unit     `protobuf:"bytes,21,rep,name=units"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Essential) Reset() {
	*x = Essential{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Essential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Essential) ProtoMessage() {}

func (x *Essential) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Essential) GetType() Essential_Type {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return Essential_UNSPECIFIED
}

func (x *Essential) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Essential) GetScopeUuid() string {
	if x != nil {
		if x.xxx_hidden_ScopeUuid != nil {
			return *x.xxx_hidden_ScopeUuid
		}
		return ""
	}
	return ""
}

func (x *Essential) GetScopeName() string {
	if x != nil {
		if x.xxx_hidden_ScopeName != nil {
			return *x.xxx_hidden_ScopeName
		}
		return ""
	}
	return ""
}

func (x *Essential) GetUnits() []*Essential_Unit {
	if x != nil {
		if x.xxx_hidden_Units != nil {
			return *x.xxx_hidden_Units
		}
	}
	return nil
}

func (x *Essential) SetType(v Essential_Type) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Essential) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Essential) SetScopeUuid(v string) {
	x.xxx_hidden_ScopeUuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Essential) SetScopeName(v string) {
	x.xxx_hidden_ScopeName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Essential) SetUnits(v []*Essential_Unit) {
	x.xxx_hidden_Units = &v
}

func (x *Essential) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Essential) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Essential) HasScopeUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Essential) HasScopeName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Essential) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = Essential_UNSPECIFIED
}

func (x *Essential) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Essential) ClearScopeUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ScopeUuid = nil
}

func (x *Essential) ClearScopeName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ScopeName = nil
}

type Essential_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type      *Essential_Type
	Name      *string
	ScopeUuid *string
	ScopeName *string
	Units     []*Essential_Unit
}

func (b0 Essential_builder) Build() *Essential {
	m0 := &Essential{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.ScopeUuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ScopeUuid = b.ScopeUuid
	}
	if b.ScopeName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_ScopeName = b.ScopeName
	}
	x.xxx_hidden_Units = &b.Units
	return m0
}

type Status struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Level       Status_Level           `protobuf:"varint,1,opt,name=level,enum=otterscale.essential.v1.Status_Level"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	xxx_hidden_Details     *string                `protobuf:"bytes,3,opt,name=details"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Status) GetLevel() Status_Level {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Level
		}
	}
	return Status_INFO
}

func (x *Status) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *Status) GetDetails() string {
	if x != nil {
		if x.xxx_hidden_Details != nil {
			return *x.xxx_hidden_Details
		}
		return ""
	}
	return ""
}

func (x *Status) SetLevel(v Status_Level) {
	x.xxx_hidden_Level = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Status) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Status) SetDetails(v string) {
	x.xxx_hidden_Details = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Status) HasLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Status) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Status) HasDetails() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Status) ClearLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Level = Status_INFO
}

func (x *Status) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

func (x *Status) ClearDetails() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Details = nil
}

type Status_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Level   *Status_Level
	Message *string
	Details *string
}

func (b0 Status_builder) Build() *Status {
	m0 := &Status{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Level != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Level = *b.Level
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Message = b.Message
	}
	if b.Details != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Details = b.Details
	}
	return m0
}

type IsMachineDeployedRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ScopeUuid   *string                `protobuf:"bytes,1,opt,name=scope_uuid,json=scopeUuid"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IsMachineDeployedRequest) Reset() {
	*x = IsMachineDeployedRequest{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMachineDeployedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMachineDeployedRequest) ProtoMessage() {}

func (x *IsMachineDeployedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IsMachineDeployedRequest) GetScopeUuid() string {
	if x != nil {
		if x.xxx_hidden_ScopeUuid != nil {
			return *x.xxx_hidden_ScopeUuid
		}
		return ""
	}
	return ""
}

func (x *IsMachineDeployedRequest) SetScopeUuid(v string) {
	x.xxx_hidden_ScopeUuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *IsMachineDeployedRequest) HasScopeUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *IsMachineDeployedRequest) ClearScopeUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ScopeUuid = nil
}

type IsMachineDeployedRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ScopeUuid *string
}

func (b0 IsMachineDeployedRequest_builder) Build() *IsMachineDeployedRequest {
	m0 := &IsMachineDeployedRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ScopeUuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ScopeUuid = b.ScopeUuid
	}
	return m0
}

type IsMachineDeployedResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Deployed    bool                   `protobuf:"varint,1,opt,name=deployed"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IsMachineDeployedResponse) Reset() {
	*x = IsMachineDeployedResponse{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMachineDeployedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMachineDeployedResponse) ProtoMessage() {}

func (x *IsMachineDeployedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IsMachineDeployedResponse) GetDeployed() bool {
	if x != nil {
		return x.xxx_hidden_Deployed
	}
	return false
}

func (x *IsMachineDeployedResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *IsMachineDeployedResponse) SetDeployed(v bool) {
	x.xxx_hidden_Deployed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *IsMachineDeployedResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *IsMachineDeployedResponse) HasDeployed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *IsMachineDeployedResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *IsMachineDeployedResponse) ClearDeployed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Deployed = false
}

func (x *IsMachineDeployedResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type IsMachineDeployedResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Deployed *bool
	Message  *string
}

func (b0 IsMachineDeployedResponse_builder) Build() *IsMachineDeployedResponse {
	m0 := &IsMachineDeployedResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Deployed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Deployed = *b.Deployed
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

type ListStatusesRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ScopeUuid   *string                `protobuf:"bytes,1,opt,name=scope_uuid,json=scopeUuid"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListStatusesRequest) Reset() {
	*x = ListStatusesRequest{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatusesRequest) ProtoMessage() {}

func (x *ListStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListStatusesRequest) GetScopeUuid() string {
	if x != nil {
		if x.xxx_hidden_ScopeUuid != nil {
			return *x.xxx_hidden_ScopeUuid
		}
		return ""
	}
	return ""
}

func (x *ListStatusesRequest) SetScopeUuid(v string) {
	x.xxx_hidden_ScopeUuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ListStatusesRequest) HasScopeUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListStatusesRequest) ClearScopeUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ScopeUuid = nil
}

type ListStatusesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ScopeUuid *string
}

func (b0 ListStatusesRequest_builder) Build() *ListStatusesRequest {
	m0 := &ListStatusesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ScopeUuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ScopeUuid = b.ScopeUuid
	}
	return m0
}

type ListStatusesResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Statuses *[]*Status             `protobuf:"bytes,1,rep,name=statuses"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListStatusesResponse) Reset() {
	*x = ListStatusesResponse{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatusesResponse) ProtoMessage() {}

func (x *ListStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListStatusesResponse) GetStatuses() []*Status {
	if x != nil {
		if x.xxx_hidden_Statuses != nil {
			return *x.xxx_hidden_Statuses
		}
	}
	return nil
}

func (x *ListStatusesResponse) SetStatuses(v []*Status) {
	x.xxx_hidden_Statuses = &v
}

type ListStatusesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Statuses []*Status
}

func (b0 ListStatusesResponse_builder) Build() *ListStatusesResponse {
	m0 := &ListStatusesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Statuses = &b.Statuses
	return m0
}

type ListEssentialsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        Essential_Type         `protobuf:"varint,1,opt,name=type,enum=otterscale.essential.v1.Essential_Type"`
	xxx_hidden_ScopeUuid   *string                `protobuf:"bytes,2,opt,name=scope_uuid,json=scopeUuid"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListEssentialsRequest) Reset() {
	*x = ListEssentialsRequest{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEssentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEssentialsRequest) ProtoMessage() {}

func (x *ListEssentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListEssentialsRequest) GetType() Essential_Type {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return Essential_UNSPECIFIED
}

func (x *ListEssentialsRequest) GetScopeUuid() string {
	if x != nil {
		if x.xxx_hidden_ScopeUuid != nil {
			return *x.xxx_hidden_ScopeUuid
		}
		return ""
	}
	return ""
}

func (x *ListEssentialsRequest) SetType(v Essential_Type) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ListEssentialsRequest) SetScopeUuid(v string) {
	x.xxx_hidden_ScopeUuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ListEssentialsRequest) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListEssentialsRequest) HasScopeUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListEssentialsRequest) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = Essential_UNSPECIFIED
}

func (x *ListEssentialsRequest) ClearScopeUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ScopeUuid = nil
}

type ListEssentialsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type      *Essential_Type
	ScopeUuid *string
}

func (b0 ListEssentialsRequest_builder) Build() *ListEssentialsRequest {
	m0 := &ListEssentialsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Type = *b.Type
	}
	if b.ScopeUuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ScopeUuid = b.ScopeUuid
	}
	return m0
}

type ListEssentialsResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Essentials *[]*Essential          `protobuf:"bytes,1,rep,name=essentials"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListEssentialsResponse) Reset() {
	*x = ListEssentialsResponse{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEssentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEssentialsResponse) ProtoMessage() {}

func (x *ListEssentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListEssentialsResponse) GetEssentials() []*Essential {
	if x != nil {
		if x.xxx_hidden_Essentials != nil {
			return *x.xxx_hidden_Essentials
		}
	}
	return nil
}

func (x *ListEssentialsResponse) SetEssentials(v []*Essential) {
	x.xxx_hidden_Essentials = &v
}

type ListEssentialsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Essentials []*Essential
}

func (b0 ListEssentialsResponse_builder) Build() *ListEssentialsResponse {
	m0 := &ListEssentialsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Essentials = &b.Essentials
	return m0
}

type CreateSingleNodeRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ScopeUuid   *string                `protobuf:"bytes,1,opt,name=scope_uuid,json=scopeUuid"`
	xxx_hidden_MachineId   *string                `protobuf:"bytes,2,opt,name=machine_id,json=machineId"`
	xxx_hidden_PrefixName  *string                `protobuf:"bytes,3,opt,name=prefix_name,json=prefixName"`
	xxx_hidden_VirtualIps  []string               `protobuf:"bytes,11,rep,name=virtual_ips,json=virtualIps"`
	xxx_hidden_CalicoCidr  *string                `protobuf:"bytes,12,opt,name=calico_cidr,json=calicoCidr"`
	xxx_hidden_OsdDevices  []string               `protobuf:"bytes,21,rep,name=osd_devices,json=osdDevices"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateSingleNodeRequest) Reset() {
	*x = CreateSingleNodeRequest{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSingleNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSingleNodeRequest) ProtoMessage() {}

func (x *CreateSingleNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSingleNodeRequest) GetScopeUuid() string {
	if x != nil {
		if x.xxx_hidden_ScopeUuid != nil {
			return *x.xxx_hidden_ScopeUuid
		}
		return ""
	}
	return ""
}

func (x *CreateSingleNodeRequest) GetMachineId() string {
	if x != nil {
		if x.xxx_hidden_MachineId != nil {
			return *x.xxx_hidden_MachineId
		}
		return ""
	}
	return ""
}

func (x *CreateSingleNodeRequest) GetPrefixName() string {
	if x != nil {
		if x.xxx_hidden_PrefixName != nil {
			return *x.xxx_hidden_PrefixName
		}
		return ""
	}
	return ""
}

func (x *CreateSingleNodeRequest) GetVirtualIps() []string {
	if x != nil {
		return x.xxx_hidden_VirtualIps
	}
	return nil
}

func (x *CreateSingleNodeRequest) GetCalicoCidr() string {
	if x != nil {
		if x.xxx_hidden_CalicoCidr != nil {
			return *x.xxx_hidden_CalicoCidr
		}
		return ""
	}
	return ""
}

func (x *CreateSingleNodeRequest) GetOsdDevices() []string {
	if x != nil {
		return x.xxx_hidden_OsdDevices
	}
	return nil
}

func (x *CreateSingleNodeRequest) SetScopeUuid(v string) {
	x.xxx_hidden_ScopeUuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *CreateSingleNodeRequest) SetMachineId(v string) {
	x.xxx_hidden_MachineId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *CreateSingleNodeRequest) SetPrefixName(v string) {
	x.xxx_hidden_PrefixName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *CreateSingleNodeRequest) SetVirtualIps(v []string) {
	x.xxx_hidden_VirtualIps = v
}

func (x *CreateSingleNodeRequest) SetCalicoCidr(v string) {
	x.xxx_hidden_CalicoCidr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *CreateSingleNodeRequest) SetOsdDevices(v []string) {
	x.xxx_hidden_OsdDevices = v
}

func (x *CreateSingleNodeRequest) HasScopeUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateSingleNodeRequest) HasMachineId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateSingleNodeRequest) HasPrefixName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateSingleNodeRequest) HasCalicoCidr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateSingleNodeRequest) ClearScopeUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ScopeUuid = nil
}

func (x *CreateSingleNodeRequest) ClearMachineId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MachineId = nil
}

func (x *CreateSingleNodeRequest) ClearPrefixName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_PrefixName = nil
}

func (x *CreateSingleNodeRequest) ClearCalicoCidr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CalicoCidr = nil
}

type CreateSingleNodeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ScopeUuid  *string
	MachineId  *string
	PrefixName *string
	VirtualIps []string
	CalicoCidr *string
	OsdDevices []string
}

func (b0 CreateSingleNodeRequest_builder) Build() *CreateSingleNodeRequest {
	m0 := &CreateSingleNodeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ScopeUuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_ScopeUuid = b.ScopeUuid
	}
	if b.MachineId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_MachineId = b.MachineId
	}
	if b.PrefixName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_PrefixName = b.PrefixName
	}
	x.xxx_hidden_VirtualIps = b.VirtualIps
	if b.CalicoCidr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_CalicoCidr = b.CalicoCidr
	}
	x.xxx_hidden_OsdDevices = b.OsdDevices
	return m0
}

type CreateHighAvailabilityClusterRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ScopeUuid   *string                `protobuf:"bytes,1,opt,name=scope_uuid,json=scopeUuid"`
	xxx_hidden_MachineId   *string                `protobuf:"bytes,2,opt,name=machine_id,json=machineId"`
	xxx_hidden_PrefixName  *string                `protobuf:"bytes,3,opt,name=prefix_name,json=prefixName"`
	xxx_hidden_VirtualIps  []string               `protobuf:"bytes,11,rep,name=virtual_ips,json=virtualIps"`
	xxx_hidden_CalicoCidr  *string                `protobuf:"bytes,12,opt,name=calico_cidr,json=calicoCidr"`
	xxx_hidden_OsdDevices  []string               `protobuf:"bytes,21,rep,name=osd_devices,json=osdDevices"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateHighAvailabilityClusterRequest) Reset() {
	*x = CreateHighAvailabilityClusterRequest{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHighAvailabilityClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHighAvailabilityClusterRequest) ProtoMessage() {}

func (x *CreateHighAvailabilityClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateHighAvailabilityClusterRequest) GetScopeUuid() string {
	if x != nil {
		if x.xxx_hidden_ScopeUuid != nil {
			return *x.xxx_hidden_ScopeUuid
		}
		return ""
	}
	return ""
}

func (x *CreateHighAvailabilityClusterRequest) GetMachineId() string {
	if x != nil {
		if x.xxx_hidden_MachineId != nil {
			return *x.xxx_hidden_MachineId
		}
		return ""
	}
	return ""
}

func (x *CreateHighAvailabilityClusterRequest) GetPrefixName() string {
	if x != nil {
		if x.xxx_hidden_PrefixName != nil {
			return *x.xxx_hidden_PrefixName
		}
		return ""
	}
	return ""
}

func (x *CreateHighAvailabilityClusterRequest) GetVirtualIps() []string {
	if x != nil {
		return x.xxx_hidden_VirtualIps
	}
	return nil
}

func (x *CreateHighAvailabilityClusterRequest) GetCalicoCidr() string {
	if x != nil {
		if x.xxx_hidden_CalicoCidr != nil {
			return *x.xxx_hidden_CalicoCidr
		}
		return ""
	}
	return ""
}

func (x *CreateHighAvailabilityClusterRequest) GetOsdDevices() []string {
	if x != nil {
		return x.xxx_hidden_OsdDevices
	}
	return nil
}

func (x *CreateHighAvailabilityClusterRequest) SetScopeUuid(v string) {
	x.xxx_hidden_ScopeUuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *CreateHighAvailabilityClusterRequest) SetMachineId(v string) {
	x.xxx_hidden_MachineId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *CreateHighAvailabilityClusterRequest) SetPrefixName(v string) {
	x.xxx_hidden_PrefixName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *CreateHighAvailabilityClusterRequest) SetVirtualIps(v []string) {
	x.xxx_hidden_VirtualIps = v
}

func (x *CreateHighAvailabilityClusterRequest) SetCalicoCidr(v string) {
	x.xxx_hidden_CalicoCidr = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *CreateHighAvailabilityClusterRequest) SetOsdDevices(v []string) {
	x.xxx_hidden_OsdDevices = v
}

func (x *CreateHighAvailabilityClusterRequest) HasScopeUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateHighAvailabilityClusterRequest) HasMachineId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateHighAvailabilityClusterRequest) HasPrefixName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateHighAvailabilityClusterRequest) HasCalicoCidr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CreateHighAvailabilityClusterRequest) ClearScopeUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ScopeUuid = nil
}

func (x *CreateHighAvailabilityClusterRequest) ClearMachineId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MachineId = nil
}

func (x *CreateHighAvailabilityClusterRequest) ClearPrefixName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_PrefixName = nil
}

func (x *CreateHighAvailabilityClusterRequest) ClearCalicoCidr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CalicoCidr = nil
}

type CreateHighAvailabilityClusterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ScopeUuid  *string
	MachineId  *string
	PrefixName *string
	VirtualIps []string
	CalicoCidr *string
	OsdDevices []string
}

func (b0 CreateHighAvailabilityClusterRequest_builder) Build() *CreateHighAvailabilityClusterRequest {
	m0 := &CreateHighAvailabilityClusterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ScopeUuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_ScopeUuid = b.ScopeUuid
	}
	if b.MachineId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_MachineId = b.MachineId
	}
	if b.PrefixName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_PrefixName = b.PrefixName
	}
	x.xxx_hidden_VirtualIps = b.VirtualIps
	if b.CalicoCidr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_CalicoCidr = b.CalicoCidr
	}
	x.xxx_hidden_OsdDevices = b.OsdDevices
	return m0
}

type AddUnitsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        Essential_Type         `protobuf:"varint,1,opt,name=type,enum=otterscale.essential.v1.Essential_Type"`
	xxx_hidden_ScopeUuid   *string                `protobuf:"bytes,2,opt,name=scope_uuid,json=scopeUuid"`
	xxx_hidden_Name        *string                `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_Number      int32                  `protobuf:"varint,4,opt,name=number"`
	xxx_hidden_MachineIds  []string               `protobuf:"bytes,5,rep,name=machine_ids,json=machineIds"`
	xxx_hidden_Force       bool                   `protobuf:"varint,11,opt,name=force"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddUnitsRequest) Reset() {
	*x = AddUnitsRequest{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUnitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUnitsRequest) ProtoMessage() {}

func (x *AddUnitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddUnitsRequest) GetType() Essential_Type {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return Essential_UNSPECIFIED
}

func (x *AddUnitsRequest) GetScopeUuid() string {
	if x != nil {
		if x.xxx_hidden_ScopeUuid != nil {
			return *x.xxx_hidden_ScopeUuid
		}
		return ""
	}
	return ""
}

func (x *AddUnitsRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *AddUnitsRequest) GetNumber() int32 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *AddUnitsRequest) GetMachineIds() []string {
	if x != nil {
		return x.xxx_hidden_MachineIds
	}
	return nil
}

func (x *AddUnitsRequest) GetForce() bool {
	if x != nil {
		return x.xxx_hidden_Force
	}
	return false
}

func (x *AddUnitsRequest) SetType(v Essential_Type) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *AddUnitsRequest) SetScopeUuid(v string) {
	x.xxx_hidden_ScopeUuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *AddUnitsRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *AddUnitsRequest) SetNumber(v int32) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *AddUnitsRequest) SetMachineIds(v []string) {
	x.xxx_hidden_MachineIds = v
}

func (x *AddUnitsRequest) SetForce(v bool) {
	x.xxx_hidden_Force = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *AddUnitsRequest) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AddUnitsRequest) HasScopeUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AddUnitsRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AddUnitsRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AddUnitsRequest) HasForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *AddUnitsRequest) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = Essential_UNSPECIFIED
}

func (x *AddUnitsRequest) ClearScopeUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ScopeUuid = nil
}

func (x *AddUnitsRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *AddUnitsRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Number = 0
}

func (x *AddUnitsRequest) ClearForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Force = false
}

type AddUnitsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type       *Essential_Type
	ScopeUuid  *string
	Name       *string
	Number     *int32
	MachineIds []string
	Force      *bool
}

func (b0 AddUnitsRequest_builder) Build() *AddUnitsRequest {
	m0 := &AddUnitsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Type = *b.Type
	}
	if b.ScopeUuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_ScopeUuid = b.ScopeUuid
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Number = *b.Number
	}
	x.xxx_hidden_MachineIds = b.MachineIds
	if b.Force != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Force = *b.Force
	}
	return m0
}

type ListKubernetesNodeLabelsRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ScopeUuid    *string                `protobuf:"bytes,1,opt,name=scope_uuid,json=scopeUuid"`
	xxx_hidden_FacilityName *string                `protobuf:"bytes,2,opt,name=facility_name,json=facilityName"`
	xxx_hidden_Hostname     *string                `protobuf:"bytes,3,opt,name=hostname"`
	xxx_hidden_All          bool                   `protobuf:"varint,11,opt,name=all"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListKubernetesNodeLabelsRequest) Reset() {
	*x = ListKubernetesNodeLabelsRequest{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKubernetesNodeLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKubernetesNodeLabelsRequest) ProtoMessage() {}

func (x *ListKubernetesNodeLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListKubernetesNodeLabelsRequest) GetScopeUuid() string {
	if x != nil {
		if x.xxx_hidden_ScopeUuid != nil {
			return *x.xxx_hidden_ScopeUuid
		}
		return ""
	}
	return ""
}

func (x *ListKubernetesNodeLabelsRequest) GetFacilityName() string {
	if x != nil {
		if x.xxx_hidden_FacilityName != nil {
			return *x.xxx_hidden_FacilityName
		}
		return ""
	}
	return ""
}

func (x *ListKubernetesNodeLabelsRequest) GetHostname() string {
	if x != nil {
		if x.xxx_hidden_Hostname != nil {
			return *x.xxx_hidden_Hostname
		}
		return ""
	}
	return ""
}

func (x *ListKubernetesNodeLabelsRequest) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *ListKubernetesNodeLabelsRequest) SetScopeUuid(v string) {
	x.xxx_hidden_ScopeUuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ListKubernetesNodeLabelsRequest) SetFacilityName(v string) {
	x.xxx_hidden_FacilityName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ListKubernetesNodeLabelsRequest) SetHostname(v string) {
	x.xxx_hidden_Hostname = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ListKubernetesNodeLabelsRequest) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ListKubernetesNodeLabelsRequest) HasScopeUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListKubernetesNodeLabelsRequest) HasFacilityName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListKubernetesNodeLabelsRequest) HasHostname() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListKubernetesNodeLabelsRequest) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ListKubernetesNodeLabelsRequest) ClearScopeUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ScopeUuid = nil
}

func (x *ListKubernetesNodeLabelsRequest) ClearFacilityName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_FacilityName = nil
}

func (x *ListKubernetesNodeLabelsRequest) ClearHostname() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Hostname = nil
}

func (x *ListKubernetesNodeLabelsRequest) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_All = false
}

type ListKubernetesNodeLabelsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ScopeUuid    *string
	FacilityName *string
	Hostname     *string
	All          *bool
}

func (b0 ListKubernetesNodeLabelsRequest_builder) Build() *ListKubernetesNodeLabelsRequest {
	m0 := &ListKubernetesNodeLabelsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ScopeUuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ScopeUuid = b.ScopeUuid
	}
	if b.FacilityName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_FacilityName = b.FacilityName
	}
	if b.Hostname != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Hostname = b.Hostname
	}
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_All = *b.All
	}
	return m0
}

type ListKubernetesNodeLabelsResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Labels map[string]string      `protobuf:"bytes,1,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListKubernetesNodeLabelsResponse) Reset() {
	*x = ListKubernetesNodeLabelsResponse{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKubernetesNodeLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKubernetesNodeLabelsResponse) ProtoMessage() {}

func (x *ListKubernetesNodeLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListKubernetesNodeLabelsResponse) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *ListKubernetesNodeLabelsResponse) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

type ListKubernetesNodeLabelsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Labels map[string]string
}

func (b0 ListKubernetesNodeLabelsResponse_builder) Build() *ListKubernetesNodeLabelsResponse {
	m0 := &ListKubernetesNodeLabelsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type UpdateKubernetesNodeLabelsRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ScopeUuid    *string                `protobuf:"bytes,1,opt,name=scope_uuid,json=scopeUuid"`
	xxx_hidden_FacilityName *string                `protobuf:"bytes,2,opt,name=facility_name,json=facilityName"`
	xxx_hidden_Hostname     *string                `protobuf:"bytes,3,opt,name=hostname"`
	xxx_hidden_Labels       map[string]string      `protobuf:"bytes,4,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateKubernetesNodeLabelsRequest) Reset() {
	*x = UpdateKubernetesNodeLabelsRequest{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKubernetesNodeLabelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKubernetesNodeLabelsRequest) ProtoMessage() {}

func (x *UpdateKubernetesNodeLabelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateKubernetesNodeLabelsRequest) GetScopeUuid() string {
	if x != nil {
		if x.xxx_hidden_ScopeUuid != nil {
			return *x.xxx_hidden_ScopeUuid
		}
		return ""
	}
	return ""
}

func (x *UpdateKubernetesNodeLabelsRequest) GetFacilityName() string {
	if x != nil {
		if x.xxx_hidden_FacilityName != nil {
			return *x.xxx_hidden_FacilityName
		}
		return ""
	}
	return ""
}

func (x *UpdateKubernetesNodeLabelsRequest) GetHostname() string {
	if x != nil {
		if x.xxx_hidden_Hostname != nil {
			return *x.xxx_hidden_Hostname
		}
		return ""
	}
	return ""
}

func (x *UpdateKubernetesNodeLabelsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *UpdateKubernetesNodeLabelsRequest) SetScopeUuid(v string) {
	x.xxx_hidden_ScopeUuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *UpdateKubernetesNodeLabelsRequest) SetFacilityName(v string) {
	x.xxx_hidden_FacilityName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *UpdateKubernetesNodeLabelsRequest) SetHostname(v string) {
	x.xxx_hidden_Hostname = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *UpdateKubernetesNodeLabelsRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *UpdateKubernetesNodeLabelsRequest) HasScopeUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateKubernetesNodeLabelsRequest) HasFacilityName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateKubernetesNodeLabelsRequest) HasHostname() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateKubernetesNodeLabelsRequest) ClearScopeUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ScopeUuid = nil
}

func (x *UpdateKubernetesNodeLabelsRequest) ClearFacilityName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_FacilityName = nil
}

func (x *UpdateKubernetesNodeLabelsRequest) ClearHostname() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Hostname = nil
}

type UpdateKubernetesNodeLabelsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ScopeUuid    *string
	FacilityName *string
	Hostname     *string
	Labels       map[string]string
}

func (b0 UpdateKubernetesNodeLabelsRequest_builder) Build() *UpdateKubernetesNodeLabelsRequest {
	m0 := &UpdateKubernetesNodeLabelsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ScopeUuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_ScopeUuid = b.ScopeUuid
	}
	if b.FacilityName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_FacilityName = b.FacilityName
	}
	if b.Hostname != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Hostname = b.Hostname
	}
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type UpdateKubernetesNodeLabelsResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Labels map[string]string      `protobuf:"bytes,1,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateKubernetesNodeLabelsResponse) Reset() {
	*x = UpdateKubernetesNodeLabelsResponse{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKubernetesNodeLabelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKubernetesNodeLabelsResponse) ProtoMessage() {}

func (x *UpdateKubernetesNodeLabelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateKubernetesNodeLabelsResponse) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *UpdateKubernetesNodeLabelsResponse) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

type UpdateKubernetesNodeLabelsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Labels map[string]string
}

func (b0 UpdateKubernetesNodeLabelsResponse_builder) Build() *UpdateKubernetesNodeLabelsResponse {
	m0 := &UpdateKubernetesNodeLabelsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type Essential_Unit struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Directive   *string                `protobuf:"bytes,2,opt,name=directive"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Essential_Unit) Reset() {
	*x = Essential_Unit{}
	mi := &file_api_essential_v1_essential_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Essential_Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Essential_Unit) ProtoMessage() {}

func (x *Essential_Unit) ProtoReflect() protoreflect.Message {
	mi := &file_api_essential_v1_essential_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Essential_Unit) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Essential_Unit) GetDirective() string {
	if x != nil {
		if x.xxx_hidden_Directive != nil {
			return *x.xxx_hidden_Directive
		}
		return ""
	}
	return ""
}

func (x *Essential_Unit) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Essential_Unit) SetDirective(v string) {
	x.xxx_hidden_Directive = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Essential_Unit) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Essential_Unit) HasDirective() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Essential_Unit) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Essential_Unit) ClearDirective() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Directive = nil
}

type Essential_Unit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name      *string
	Directive *string
}

func (b0 Essential_Unit_builder) Build() *Essential_Unit {
	m0 := &Essential_Unit{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Directive != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Directive = b.Directive
	}
	return m0
}

var File_api_essential_v1_essential_proto protoreflect.FileDescriptor

const file_api_essential_v1_essential_proto_rawDesc = "" +
	"\n" +
	" api/essential/v1/essential.proto\x12\x17otterscale.essential.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xc6\x02\n" +
	"\tEssential\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.otterscale.essential.v1.Essential.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"scope_uuid\x18\v \x01(\tR\tscopeUuid\x12\x1d\n" +
	"\n" +
	"scope_name\x18\f \x01(\tR\tscopeName\x12=\n" +
	"\x05units\x18\x15 \x03(\v2'.otterscale.essential.v1.Essential.UnitR\x05units\x1a8\n" +
	"\x04Unit\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tdirective\x18\x02 \x01(\tR\tdirective\"1\n" +
	"\x04Type\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KUBERNETES\x10\x01\x12\b\n" +
	"\x04CEPH\x10\x02\"\xb9\x01\n" +
	"\x06Status\x12;\n" +
	"\x05level\x18\x01 \x01(\x0e2%.otterscale.essential.v1.Status.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\">\n" +
	"\x05Level\x12\b\n" +
	"\x04INFO\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04\"9\n" +
	"\x18IsMachineDeployedRequest\x12\x1d\n" +
	"\n" +
	"scope_uuid\x18\x01 \x01(\tR\tscopeUuid\"Q\n" +
	"\x19IsMachineDeployedResponse\x12\x1a\n" +
	"\bdeployed\x18\x01 \x01(\bR\bdeployed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x13ListStatusesRequest\x12\x1d\n" +
	"\n" +
	"scope_uuid\x18\x01 \x01(\tR\tscopeUuid\"S\n" +
	"\x14ListStatusesResponse\x12;\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1f.otterscale.essential.v1.StatusR\bstatuses\"s\n" +
	"\x15ListEssentialsRequest\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.otterscale.essential.v1.Essential.TypeR\x04type\x12\x1d\n" +
	"\n" +
	"scope_uuid\x18\x02 \x01(\tR\tscopeUuid\"\\\n" +
	"\x16ListEssentialsResponse\x12B\n" +
	"\n" +
	"essentials\x18\x01 \x03(\v2\".otterscale.essential.v1.EssentialR\n" +
	"essentials\"\xdb\x01\n" +
	"\x17CreateSingleNodeRequest\x12\x1d\n" +
	"\n" +
	"scope_uuid\x18\x01 \x01(\tR\tscopeUuid\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x12\x1f\n" +
	"\vprefix_name\x18\x03 \x01(\tR\n" +
	"prefixName\x12\x1f\n" +
	"\vvirtual_ips\x18\v \x03(\tR\n" +
	"virtualIps\x12\x1f\n" +
	"\vcalico_cidr\x18\f \x01(\tR\n" +
	"calicoCidr\x12\x1f\n" +
	"\vosd_devices\x18\x15 \x03(\tR\n" +
	"osdDevices\"\xe8\x01\n" +
	"$CreateHighAvailabilityClusterRequest\x12\x1d\n" +
	"\n" +
	"scope_uuid\x18\x01 \x01(\tR\tscopeUuid\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x12\x1f\n" +
	"\vprefix_name\x18\x03 \x01(\tR\n" +
	"prefixName\x12\x1f\n" +
	"\vvirtual_ips\x18\v \x03(\tR\n" +
	"virtualIps\x12\x1f\n" +
	"\vcalico_cidr\x18\f \x01(\tR\n" +
	"calicoCidr\x12\x1f\n" +
	"\vosd_devices\x18\x15 \x03(\tR\n" +
	"osdDevices\"\xd0\x01\n" +
	"\x0fAddUnitsRequest\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.otterscale.essential.v1.Essential.TypeR\x04type\x12\x1d\n" +
	"\n" +
	"scope_uuid\x18\x02 \x01(\tR\tscopeUuid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x12\x1f\n" +
	"\vmachine_ids\x18\x05 \x03(\tR\n" +
	"machineIds\x12\x14\n" +
	"\x05force\x18\v \x01(\bR\x05force\"\x93\x01\n" +
	"\x1fListKubernetesNodeLabelsRequest\x12\x1d\n" +
	"\n" +
	"scope_uuid\x18\x01 \x01(\tR\tscopeUuid\x12#\n" +
	"\rfacility_name\x18\x02 \x01(\tR\ffacilityName\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x10\n" +
	"\x03all\x18\v \x01(\bR\x03all\"\xbc\x01\n" +
	" ListKubernetesNodeLabelsResponse\x12]\n" +
	"\x06labels\x18\x01 \x03(\v2E.otterscale.essential.v1.ListKubernetesNodeLabelsResponse.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"!UpdateKubernetesNodeLabelsRequest\x12\x1d\n" +
	"\n" +
	"scope_uuid\x18\x01 \x01(\tR\tscopeUuid\x12#\n" +
	"\rfacility_name\x18\x02 \x01(\tR\ffacilityName\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12^\n" +
	"\x06labels\x18\x04 \x03(\v2F.otterscale.essential.v1.UpdateKubernetesNodeLabelsRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\"UpdateKubernetesNodeLabelsResponse\x12_\n" +
	"\x06labels\x18\x01 \x03(\v2G.otterscale.essential.v1.UpdateKubernetesNodeLabelsResponse.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xbc\a\n" +
	"\x10EssentialService\x12z\n" +
	"\x11IsMachineDeployed\x121.otterscale.essential.v1.IsMachineDeployedRequest\x1a2.otterscale.essential.v1.IsMachineDeployedResponse\x12k\n" +
	"\fListStatuses\x12,.otterscale.essential.v1.ListStatusesRequest\x1a-.otterscale.essential.v1.ListStatusesResponse\x12q\n" +
	"\x0eListEssentials\x12..otterscale.essential.v1.ListEssentialsRequest\x1a/.otterscale.essential.v1.ListEssentialsResponse\x12\\\n" +
	"\x10CreateSingleNode\x120.otterscale.essential.v1.CreateSingleNodeRequest\x1a\x16.google.protobuf.Empty\x12v\n" +
	"\x1dCreateHighAvailabilityCluster\x12=.otterscale.essential.v1.CreateHighAvailabilityClusterRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\bAddUnits\x12(.otterscale.essential.v1.AddUnitsRequest\x1a\x16.google.protobuf.Empty\x12\x8f\x01\n" +
	"\x18ListKubernetesNodeLabels\x128.otterscale.essential.v1.ListKubernetesNodeLabelsRequest\x1a9.otterscale.essential.v1.ListKubernetesNodeLabelsResponse\x12\x95\x01\n" +
	"\x1aUpdateKubernetesNodeLabels\x12:.otterscale.essential.v1.UpdateKubernetesNodeLabelsRequest\x1a;.otterscale.essential.v1.UpdateKubernetesNodeLabelsResponseB6Z4github.com/otterscale/otterscale/api/essential/v1;pbb\beditionsp\xe8\a"

var file_api_essential_v1_essential_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_essential_v1_essential_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_essential_v1_essential_proto_goTypes = []any{
	(Essential_Type)(0),                          // 0: otterscale.essential.v1.Essential.Type
	(Status_Level)(0),                            // 1: otterscale.essential.v1.Status.Level
	(*Essential)(nil),                            // 2: otterscale.essential.v1.Essential
	(*Status)(nil),                               // 3: otterscale.essential.v1.Status
	(*IsMachineDeployedRequest)(nil),             // 4: otterscale.essential.v1.IsMachineDeployedRequest
	(*IsMachineDeployedResponse)(nil),            // 5: otterscale.essential.v1.IsMachineDeployedResponse
	(*ListStatusesRequest)(nil),                  // 6: otterscale.essential.v1.ListStatusesRequest
	(*ListStatusesResponse)(nil),                 // 7: otterscale.essential.v1.ListStatusesResponse
	(*ListEssentialsRequest)(nil),                // 8: otterscale.essential.v1.ListEssentialsRequest
	(*ListEssentialsResponse)(nil),               // 9: otterscale.essential.v1.ListEssentialsResponse
	(*CreateSingleNodeRequest)(nil),              // 10: otterscale.essential.v1.CreateSingleNodeRequest
	(*CreateHighAvailabilityClusterRequest)(nil), // 11: otterscale.essential.v1.CreateHighAvailabilityClusterRequest
	(*AddUnitsRequest)(nil),                      // 12: otterscale.essential.v1.AddUnitsRequest
	(*ListKubernetesNodeLabelsRequest)(nil),      // 13: otterscale.essential.v1.ListKubernetesNodeLabelsRequest
	(*ListKubernetesNodeLabelsResponse)(nil),     // 14: otterscale.essential.v1.ListKubernetesNodeLabelsResponse
	(*UpdateKubernetesNodeLabelsRequest)(nil),    // 15: otterscale.essential.v1.UpdateKubernetesNodeLabelsRequest
	(*UpdateKubernetesNodeLabelsResponse)(nil),   // 16: otterscale.essential.v1.UpdateKubernetesNodeLabelsResponse
	(*Essential_Unit)(nil),                       // 17: otterscale.essential.v1.Essential.Unit
	nil,                                          // 18: otterscale.essential.v1.ListKubernetesNodeLabelsResponse.LabelsEntry
	nil,                                          // 19: otterscale.essential.v1.UpdateKubernetesNodeLabelsRequest.LabelsEntry
	nil,                                          // 20: otterscale.essential.v1.UpdateKubernetesNodeLabelsResponse.LabelsEntry
	(*emptypb.Empty)(nil),                        // 21: google.protobuf.Empty
}
var file_api_essential_v1_essential_proto_depIdxs = []int32{
	0,  // 0: otterscale.essential.v1.Essential.type:type_name -> otterscale.essential.v1.Essential.Type
	17, // 1: otterscale.essential.v1.Essential.units:type_name -> otterscale.essential.v1.Essential.Unit
	1,  // 2: otterscale.essential.v1.Status.level:type_name -> otterscale.essential.v1.Status.Level
	3,  // 3: otterscale.essential.v1.ListStatusesResponse.statuses:type_name -> otterscale.essential.v1.Status
	0,  // 4: otterscale.essential.v1.ListEssentialsRequest.type:type_name -> otterscale.essential.v1.Essential.Type
	2,  // 5: otterscale.essential.v1.ListEssentialsResponse.essentials:type_name -> otterscale.essential.v1.Essential
	0,  // 6: otterscale.essential.v1.AddUnitsRequest.type:type_name -> otterscale.essential.v1.Essential.Type
	18, // 7: otterscale.essential.v1.ListKubernetesNodeLabelsResponse.labels:type_name -> otterscale.essential.v1.ListKubernetesNodeLabelsResponse.LabelsEntry
	19, // 8: otterscale.essential.v1.UpdateKubernetesNodeLabelsRequest.labels:type_name -> otterscale.essential.v1.UpdateKubernetesNodeLabelsRequest.LabelsEntry
	20, // 9: otterscale.essential.v1.UpdateKubernetesNodeLabelsResponse.labels:type_name -> otterscale.essential.v1.UpdateKubernetesNodeLabelsResponse.LabelsEntry
	4,  // 10: otterscale.essential.v1.EssentialService.IsMachineDeployed:input_type -> otterscale.essential.v1.IsMachineDeployedRequest
	6,  // 11: otterscale.essential.v1.EssentialService.ListStatuses:input_type -> otterscale.essential.v1.ListStatusesRequest
	8,  // 12: otterscale.essential.v1.EssentialService.ListEssentials:input_type -> otterscale.essential.v1.ListEssentialsRequest
	10, // 13: otterscale.essential.v1.EssentialService.CreateSingleNode:input_type -> otterscale.essential.v1.CreateSingleNodeRequest
	11, // 14: otterscale.essential.v1.EssentialService.CreateHighAvailabilityCluster:input_type -> otterscale.essential.v1.CreateHighAvailabilityClusterRequest
	12, // 15: otterscale.essential.v1.EssentialService.AddUnits:input_type -> otterscale.essential.v1.AddUnitsRequest
	13, // 16: otterscale.essential.v1.EssentialService.ListKubernetesNodeLabels:input_type -> otterscale.essential.v1.ListKubernetesNodeLabelsRequest
	15, // 17: otterscale.essential.v1.EssentialService.UpdateKubernetesNodeLabels:input_type -> otterscale.essential.v1.UpdateKubernetesNodeLabelsRequest
	5,  // 18: otterscale.essential.v1.EssentialService.IsMachineDeployed:output_type -> otterscale.essential.v1.IsMachineDeployedResponse
	7,  // 19: otterscale.essential.v1.EssentialService.ListStatuses:output_type -> otterscale.essential.v1.ListStatusesResponse
	9,  // 20: otterscale.essential.v1.EssentialService.ListEssentials:output_type -> otterscale.essential.v1.ListEssentialsResponse
	21, // 21: otterscale.essential.v1.EssentialService.CreateSingleNode:output_type -> google.protobuf.Empty
	21, // 22: otterscale.essential.v1.EssentialService.CreateHighAvailabilityCluster:output_type -> google.protobuf.Empty
	21, // 23: otterscale.essential.v1.EssentialService.AddUnits:output_type -> google.protobuf.Empty
	14, // 24: otterscale.essential.v1.EssentialService.ListKubernetesNodeLabels:output_type -> otterscale.essential.v1.ListKubernetesNodeLabelsResponse
	16, // 25: otterscale.essential.v1.EssentialService.UpdateKubernetesNodeLabels:output_type -> otterscale.essential.v1.UpdateKubernetesNodeLabelsResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_essential_v1_essential_proto_init() }
func file_api_essential_v1_essential_proto_init() {
	if File_api_essential_v1_essential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_essential_v1_essential_proto_rawDesc), len(file_api_essential_v1_essential_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_essential_v1_essential_proto_goTypes,
		DependencyIndexes: file_api_essential_v1_essential_proto_depIdxs,
		EnumInfos:         file_api_essential_v1_essential_proto_enumTypes,
		MessageInfos:      file_api_essential_v1_essential_proto_msgTypes,
	}.Build()
	File_api_essential_v1_essential_proto = out.File
	file_api_essential_v1_essential_proto_goTypes = nil
	file_api_essential_v1_essential_proto_depIdxs = nil
}
