// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts,import_extension=.js"
// @generated from file runtime/v1/runtime.proto (package otterscale.runtime.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file runtime/v1/runtime.proto.
 */
export declare const file_runtime_v1_runtime: GenFile;

/**
 * PodLogRequest defines the parameters for streaming container logs.
 * Fields align with corev1.PodLogOptions.
 *
 * @generated from message otterscale.runtime.v1.PodLogRequest
 */
export declare type PodLogRequest = Message<"otterscale.runtime.v1.PodLogRequest"> & {
  /**
   * The target Kubernetes cluster identifier.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;

  /**
   * The namespace of the pod.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * The name of the pod.
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * The container name. If omitted, the first container in the pod is used.
   *
   * @generated from field: string container = 4;
   */
  container: string;

  /**
   * If true, stream logs as they are produced (like `kubectl logs -f`).
   *
   * @generated from field: bool follow = 5;
   */
  follow: boolean;

  /**
   * Number of lines from the end of the logs to show. If not set, all logs are shown.
   *
   * @generated from field: int64 tail_lines = 6 [features.field_presence = EXPLICIT];
   */
  tailLines: bigint;

  /**
   * A relative time in seconds before the current time from which to show logs.
   *
   * @generated from field: int64 since_seconds = 7 [features.field_presence = EXPLICIT];
   */
  sinceSeconds: bigint;

  /**
   * An absolute time from which to show logs. Mutually exclusive with since_seconds.
   *
   * @generated from field: google.protobuf.Timestamp since_time = 8;
   */
  sinceTime?: Timestamp | undefined;

  /**
   * If true, return the logs for the previous terminated container instance.
   *
   * @generated from field: bool previous = 9;
   */
  previous: boolean;

  /**
   * If true, add an RFC3339 timestamp at the beginning of every line of log output.
   *
   * @generated from field: bool timestamps = 10;
   */
  timestamps: boolean;

  /**
   * Limit the number of bytes returned from the server.
   *
   * @generated from field: int64 limit_bytes = 11 [features.field_presence = EXPLICIT];
   */
  limitBytes: bigint;
};

/**
 * Describes the message otterscale.runtime.v1.PodLogRequest.
 * Use `create(PodLogRequestSchema)` to create a new message.
 */
export declare const PodLogRequestSchema: GenMessage<PodLogRequest>;

/**
 * PodLogResponse contains a chunk of log data.
 *
 * @generated from message otterscale.runtime.v1.PodLogResponse
 */
export declare type PodLogResponse = Message<"otterscale.runtime.v1.PodLogResponse"> & {
  /**
   * Raw log data bytes.
   *
   * @generated from field: bytes data = 1;
   */
  data: Uint8Array;
};

/**
 * Describes the message otterscale.runtime.v1.PodLogResponse.
 * Use `create(PodLogResponseSchema)` to create a new message.
 */
export declare const PodLogResponseSchema: GenMessage<PodLogResponse>;

/**
 * ExecuteTTYRequest defines the parameters for starting an interactive
 * exec session in a container. Fields align with corev1.PodExecOptions.
 *
 * @generated from message otterscale.runtime.v1.ExecuteTTYRequest
 */
export declare type ExecuteTTYRequest = Message<"otterscale.runtime.v1.ExecuteTTYRequest"> & {
  /**
   * The target Kubernetes cluster identifier.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;

  /**
   * The namespace of the pod.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * The name of the pod.
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * The container to exec into. If omitted, the first container is used.
   *
   * @generated from field: string container = 4;
   */
  container: string;

  /**
   * The command to execute (e.g. ["/bin/sh"]).
   *
   * @generated from field: repeated string command = 5;
   */
  command: string[];

  /**
   * If true, allocate a TTY for the exec session.
   *
   * @generated from field: bool tty = 6;
   */
  tty: boolean;

  /**
   * Initial terminal height in rows.
   *
   * @generated from field: uint32 rows = 7;
   */
  rows: number;

  /**
   * Initial terminal width in columns.
   *
   * @generated from field: uint32 cols = 8;
   */
  cols: number;
};

/**
 * Describes the message otterscale.runtime.v1.ExecuteTTYRequest.
 * Use `create(ExecuteTTYRequestSchema)` to create a new message.
 */
export declare const ExecuteTTYRequestSchema: GenMessage<ExecuteTTYRequest>;

/**
 * ExecuteTTYResponse streams output from the exec session.
 *
 * @generated from message otterscale.runtime.v1.ExecuteTTYResponse
 */
export declare type ExecuteTTYResponse = Message<"otterscale.runtime.v1.ExecuteTTYResponse"> & {
  /**
   * The session identifier, set only in the first response message.
   * Subsequent WriteTTY / ResizeTTY calls must reference this ID.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Stdout data from the exec session.
   *
   * @generated from field: bytes stdout = 2;
   */
  stdout: Uint8Array;

  /**
   * Stderr data from the exec session (only when tty is false).
   *
   * @generated from field: bytes stderr = 3;
   */
  stderr: Uint8Array;
};

/**
 * Describes the message otterscale.runtime.v1.ExecuteTTYResponse.
 * Use `create(ExecuteTTYResponseSchema)` to create a new message.
 */
export declare const ExecuteTTYResponseSchema: GenMessage<ExecuteTTYResponse>;

/**
 * WriteTTYRequest sends stdin data to an active exec session.
 *
 * @generated from message otterscale.runtime.v1.WriteTTYRequest
 */
export declare type WriteTTYRequest = Message<"otterscale.runtime.v1.WriteTTYRequest"> & {
  /**
   * The session identifier returned in the first ExecuteTTYResponse.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Stdin data to write.
   *
   * @generated from field: bytes stdin = 2;
   */
  stdin: Uint8Array;
};

/**
 * Describes the message otterscale.runtime.v1.WriteTTYRequest.
 * Use `create(WriteTTYRequestSchema)` to create a new message.
 */
export declare const WriteTTYRequestSchema: GenMessage<WriteTTYRequest>;

/**
 * ResizeTTYRequest updates the terminal dimensions of an exec session.
 *
 * @generated from message otterscale.runtime.v1.ResizeTTYRequest
 */
export declare type ResizeTTYRequest = Message<"otterscale.runtime.v1.ResizeTTYRequest"> & {
  /**
   * The session identifier returned in the first ExecuteTTYResponse.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * New terminal height in rows.
   *
   * @generated from field: uint32 rows = 2;
   */
  rows: number;

  /**
   * New terminal width in columns.
   *
   * @generated from field: uint32 cols = 3;
   */
  cols: number;
};

/**
 * Describes the message otterscale.runtime.v1.ResizeTTYRequest.
 * Use `create(ResizeTTYRequestSchema)` to create a new message.
 */
export declare const ResizeTTYRequestSchema: GenMessage<ResizeTTYRequest>;

/**
 * PortForwardRequest defines the parameters for starting a port-forward session.
 *
 * @generated from message otterscale.runtime.v1.PortForwardRequest
 */
export declare type PortForwardRequest = Message<"otterscale.runtime.v1.PortForwardRequest"> & {
  /**
   * The target Kubernetes cluster identifier.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;

  /**
   * The namespace of the pod.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * The name of the pod.
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * The container port to forward to.
   *
   * @generated from field: int32 port = 4;
   */
  port: number;
};

/**
 * Describes the message otterscale.runtime.v1.PortForwardRequest.
 * Use `create(PortForwardRequestSchema)` to create a new message.
 */
export declare const PortForwardRequestSchema: GenMessage<PortForwardRequest>;

/**
 * PortForwardResponse streams data received from the forwarded port.
 *
 * @generated from message otterscale.runtime.v1.PortForwardResponse
 */
export declare type PortForwardResponse = Message<"otterscale.runtime.v1.PortForwardResponse"> & {
  /**
   * The session identifier, set only in the first response message.
   * Subsequent WritePortForward calls must reference this ID.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Data received from the forwarded port on the pod.
   *
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message otterscale.runtime.v1.PortForwardResponse.
 * Use `create(PortForwardResponseSchema)` to create a new message.
 */
export declare const PortForwardResponseSchema: GenMessage<PortForwardResponse>;

/**
 * WritePortForwardRequest sends data to an active port-forward session.
 *
 * @generated from message otterscale.runtime.v1.WritePortForwardRequest
 */
export declare type WritePortForwardRequest = Message<"otterscale.runtime.v1.WritePortForwardRequest"> & {
  /**
   * The session identifier returned in the first PortForwardResponse.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Data to send to the forwarded port on the pod.
   *
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message otterscale.runtime.v1.WritePortForwardRequest.
 * Use `create(WritePortForwardRequestSchema)` to create a new message.
 */
export declare const WritePortForwardRequestSchema: GenMessage<WritePortForwardRequest>;

/**
 * ScaleRequest defines the parameters for scaling a workload.
 * Uses the Kubernetes /scale subresource for correctness.
 *
 * @generated from message otterscale.runtime.v1.ScaleRequest
 */
export declare type ScaleRequest = Message<"otterscale.runtime.v1.ScaleRequest"> & {
  /**
   * The target Kubernetes cluster identifier.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;

  /**
   * Kubernetes API Group (e.g., "apps").
   *
   * @generated from field: string group = 2;
   */
  group: string;

  /**
   * Kubernetes API Version (e.g., "v1").
   *
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * Kubernetes API Resource name in plural (e.g., "deployments").
   *
   * @generated from field: string resource = 4;
   */
  resource: string;

  /**
   * The namespace of the workload.
   *
   * @generated from field: string namespace = 5;
   */
  namespace: string;

  /**
   * The name of the workload.
   *
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * The desired number of replicas.
   *
   * @generated from field: int32 replicas = 7;
   */
  replicas: number;
};

/**
 * Describes the message otterscale.runtime.v1.ScaleRequest.
 * Use `create(ScaleRequestSchema)` to create a new message.
 */
export declare const ScaleRequestSchema: GenMessage<ScaleRequest>;

/**
 * ScaleResponse contains the updated replica count after scaling.
 *
 * @generated from message otterscale.runtime.v1.ScaleResponse
 */
export declare type ScaleResponse = Message<"otterscale.runtime.v1.ScaleResponse"> & {
  /**
   * The current number of replicas after the scale operation.
   *
   * @generated from field: int32 replicas = 1;
   */
  replicas: number;
};

/**
 * Describes the message otterscale.runtime.v1.ScaleResponse.
 * Use `create(ScaleResponseSchema)` to create a new message.
 */
export declare const ScaleResponseSchema: GenMessage<ScaleResponse>;

/**
 * RestartRequest defines the parameters for triggering a rolling restart.
 * This patches the pod template annotation with kubectl.kubernetes.io/restartedAt,
 * equivalent to `kubectl rollout restart`.
 *
 * @generated from message otterscale.runtime.v1.RestartRequest
 */
export declare type RestartRequest = Message<"otterscale.runtime.v1.RestartRequest"> & {
  /**
   * The target Kubernetes cluster identifier.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;

  /**
   * Kubernetes API Group (e.g., "apps").
   *
   * @generated from field: string group = 2;
   */
  group: string;

  /**
   * Kubernetes API Version (e.g., "v1").
   *
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * Kubernetes API Resource name in plural (e.g., "deployments").
   *
   * @generated from field: string resource = 4;
   */
  resource: string;

  /**
   * The namespace of the workload.
   *
   * @generated from field: string namespace = 5;
   */
  namespace: string;

  /**
   * The name of the workload.
   *
   * @generated from field: string name = 6;
   */
  name: string;
};

/**
 * Describes the message otterscale.runtime.v1.RestartRequest.
 * Use `create(RestartRequestSchema)` to create a new message.
 */
export declare const RestartRequestSchema: GenMessage<RestartRequest>;

/**
 * SubResourceActionRequest defines the parameters for invoking a
 * subresource action on any Kubernetes resource. This is designed for
 * operations like KubeVirt VM start/stop/restart/migrate that use PUT
 * or POST on a named subresource path.
 *
 * @generated from message otterscale.runtime.v1.SubResourceActionRequest
 */
export declare type SubResourceActionRequest = Message<"otterscale.runtime.v1.SubResourceActionRequest"> & {
  /**
   * The target Kubernetes cluster identifier.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;

  /**
   * Kubernetes API Group (e.g., "kubevirt.io").
   *
   * @generated from field: string group = 2;
   */
  group: string;

  /**
   * Kubernetes API Version (e.g., "v1").
   *
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * Kubernetes API Resource name in plural (e.g., "virtualmachines").
   *
   * @generated from field: string resource = 4;
   */
  resource: string;

  /**
   * The namespace of the resource.
   *
   * @generated from field: string namespace = 5;
   */
  namespace: string;

  /**
   * The name of the resource.
   *
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * The subresource to invoke (e.g., "start", "stop", "restart").
   *
   * @generated from field: string subresource = 7;
   */
  subresource: string;

  /**
   * The HTTP method for the subresource action. Only "PUT" and "POST"
   * are allowed; DELETE and PATCH have dedicated RPCs.
   *
   * @generated from field: string method = 8;
   */
  method: string;

  /**
   * Optional JSON body (e.g., KubeVirt StopOptions with gracePeriod).
   *
   * @generated from field: bytes body = 9;
   */
  body: Uint8Array;
};

/**
 * Describes the message otterscale.runtime.v1.SubResourceActionRequest.
 * Use `create(SubResourceActionRequestSchema)` to create a new message.
 */
export declare const SubResourceActionRequestSchema: GenMessage<SubResourceActionRequest>;

/**
 * SubResourceActionResponse contains the optional response body from
 * the subresource action.
 *
 * @generated from message otterscale.runtime.v1.SubResourceActionResponse
 */
export declare type SubResourceActionResponse = Message<"otterscale.runtime.v1.SubResourceActionResponse"> & {
  /**
   * The JSON response body returned by the API server, if any.
   *
   * @generated from field: google.protobuf.Struct result = 1;
   */
  result?: JsonObject | undefined;
};

/**
 * Describes the message otterscale.runtime.v1.SubResourceActionResponse.
 * Use `create(SubResourceActionResponseSchema)` to create a new message.
 */
export declare const SubResourceActionResponseSchema: GenMessage<SubResourceActionResponse>;

/**
 * VNCRequest defines the parameters for starting a VNC session
 * to a KubeVirt VirtualMachineInstance.
 *
 * @generated from message otterscale.runtime.v1.VNCRequest
 */
export declare type VNCRequest = Message<"otterscale.runtime.v1.VNCRequest"> & {
  /**
   * The target Kubernetes cluster identifier.
   *
   * @generated from field: string cluster = 1;
   */
  cluster: string;

  /**
   * The namespace of the VirtualMachineInstance.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * The name of the VirtualMachineInstance.
   *
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message otterscale.runtime.v1.VNCRequest.
 * Use `create(VNCRequestSchema)` to create a new message.
 */
export declare const VNCRequestSchema: GenMessage<VNCRequest>;

/**
 * VNCResponse streams raw VNC protocol data from the VMI.
 *
 * @generated from message otterscale.runtime.v1.VNCResponse
 */
export declare type VNCResponse = Message<"otterscale.runtime.v1.VNCResponse"> & {
  /**
   * The session identifier, set only in the first response message.
   * Subsequent WriteVNC calls must reference this ID.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Raw VNC protocol data received from the VMI.
   *
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message otterscale.runtime.v1.VNCResponse.
 * Use `create(VNCResponseSchema)` to create a new message.
 */
export declare const VNCResponseSchema: GenMessage<VNCResponse>;

/**
 * WriteVNCRequest sends data to an active VNC session.
 *
 * @generated from message otterscale.runtime.v1.WriteVNCRequest
 */
export declare type WriteVNCRequest = Message<"otterscale.runtime.v1.WriteVNCRequest"> & {
  /**
   * The session identifier returned in the first VNCResponse.
   *
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * Raw VNC protocol data to send to the VMI.
   *
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message otterscale.runtime.v1.WriteVNCRequest.
 * Use `create(WriteVNCRequestSchema)` to create a new message.
 */
export declare const WriteVNCRequestSchema: GenMessage<WriteVNCRequest>;

/**
 * ShowChartRequest defines parameters for retrieving chart metadata
 * from a remote Helm repository.
 *
 * @generated from message otterscale.runtime.v1.ShowChartRequest
 */
export declare type ShowChartRequest = Message<"otterscale.runtime.v1.ShowChartRequest"> & {
  /**
   * The URL of the Helm chart repository (HTTP/HTTPS or OCI).
   *
   * @generated from field: string repo_url = 1;
   */
  repoUrl: string;

  /**
   * The name of the chart within the repository.
   *
   * @generated from field: string chart_name = 2;
   */
  chartName: string;

  /**
   * The chart version to query. If empty, the latest version is used.
   *
   * @generated from field: string version = 3;
   */
  version: string;
};

/**
 * Describes the message otterscale.runtime.v1.ShowChartRequest.
 * Use `create(ShowChartRequestSchema)` to create a new message.
 */
export declare const ShowChartRequestSchema: GenMessage<ShowChartRequest>;

/**
 * ShowChartResponse contains the default values and README from
 * a Helm chart.
 *
 * @generated from message otterscale.runtime.v1.ShowChartResponse
 */
export declare type ShowChartResponse = Message<"otterscale.runtime.v1.ShowChartResponse"> & {
  /**
   * The raw content of the chart's values.yaml file.
   *
   * @generated from field: bytes values = 1;
   */
  values: Uint8Array;

  /**
   * The raw content of the chart's README.md file.
   *
   * @generated from field: bytes readme = 2;
   */
  readme: Uint8Array;
};

/**
 * Describes the message otterscale.runtime.v1.ShowChartResponse.
 * Use `create(ShowChartResponseSchema)` to create a new message.
 */
export declare const ShowChartResponseSchema: GenMessage<ShowChartResponse>;

/**
 * RuntimeService provides runtime operations for Kubernetes workloads,
 * including log streaming, interactive exec, port forwarding, scaling,
 * and rolling restarts.
 *
 * @generated from service otterscale.runtime.v1.RuntimeService
 */
export declare const RuntimeService: GenService<{
  /**
   * PodLog streams log output from a container, similar to `kubectl logs -f`.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.PodLog
   */
  podLog: {
    methodKind: "server_streaming";
    input: typeof PodLogRequestSchema;
    output: typeof PodLogResponseSchema;
  },
  /**
   * ExecuteTTY starts an interactive exec session in a container and streams
   * stdout/stderr back. Due to browser limitations, bidirectional streaming
   * cannot be used; stdin is sent via the separate WriteTTY RPC.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.ExecuteTTY
   */
  executeTTY: {
    methodKind: "server_streaming";
    input: typeof ExecuteTTYRequestSchema;
    output: typeof ExecuteTTYResponseSchema;
  },
  /**
   * WriteTTY sends stdin data to an active exec session identified by session_id.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.WriteTTY
   */
  writeTTY: {
    methodKind: "unary";
    input: typeof WriteTTYRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * ResizeTTY updates the terminal dimensions of an active exec session.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.ResizeTTY
   */
  resizeTTY: {
    methodKind: "unary";
    input: typeof ResizeTTYRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * PortForward opens a port-forward session to a pod and streams data back.
   * Due to browser limitations, bidirectional streaming cannot be used;
   * data to the pod is sent via the separate WritePortForward RPC.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.PortForward
   */
  portForward: {
    methodKind: "server_streaming";
    input: typeof PortForwardRequestSchema;
    output: typeof PortForwardResponseSchema;
  },
  /**
   * WritePortForward sends data to an active port-forward session.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.WritePortForward
   */
  writePortForward: {
    methodKind: "unary";
    input: typeof WritePortForwardRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Scale updates the replica count of a scalable workload
   * (Deployment, StatefulSet, ReplicaSet) via the /scale subresource.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.Scale
   */
  scale: {
    methodKind: "unary";
    input: typeof ScaleRequestSchema;
    output: typeof ScaleResponseSchema;
  },
  /**
   * Restart triggers a rolling restart of a workload by patching the
   * pod template annotation, equivalent to `kubectl rollout restart`.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.Restart
   */
  restart: {
    methodKind: "unary";
    input: typeof RestartRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * SubResourceAction performs a generic action on a Kubernetes
   * subresource, such as KubeVirt VM start/stop/restart. The request
   * is forwarded to kube-apiserver via impersonation, so RBAC is
   * enforced automatically. Only PUT and POST methods are allowed.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.SubResourceAction
   */
  subResourceAction: {
    methodKind: "unary";
    input: typeof SubResourceActionRequestSchema;
    output: typeof SubResourceActionResponseSchema;
  },
  /**
   * VNC opens a VNC session to a KubeVirt VirtualMachineInstance and
   * streams raw VNC protocol data back. Due to browser limitations,
   * bidirectional streaming cannot be used; data to the VMI is sent
   * via the separate WriteVNC RPC.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.VNC
   */
  vNC: {
    methodKind: "server_streaming";
    input: typeof VNCRequestSchema;
    output: typeof VNCResponseSchema;
  },
  /**
   * WriteVNC sends VNC data to an active VNC session.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.WriteVNC
   */
  writeVNC: {
    methodKind: "unary";
    input: typeof WriteVNCRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * ShowChart retrieves the default values.yaml and README.md from
   * a Helm chart in a remote repository (HTTP or OCI). This executes
   * server-side and does not require a cluster connection.
   *
   * @generated from rpc otterscale.runtime.v1.RuntimeService.ShowChart
   */
  showChart: {
    methodKind: "unary";
    input: typeof ShowChartRequestSchema;
    output: typeof ShowChartResponseSchema;
  },
}>;

