//nolint:stylecheck,gosec
package env

import "os"

const (
	OPENHDC_COMPANY_NAME              = "OPENHDC_COMPANY_NAME"
	OPENHDC_CONNECTION_STRING         = "OPENHDC_CONNECTION_STRING"
	OPENHDC_MAAS_API_URL              = "OPENHDC_MAAS_API_URL"
	OPENHDC_MAAS_API_KEY              = "OPENHDC_MAAS_API_KEY"
	OPENHDC_MAAS_API_VERSION          = "OPENHDC_MAAS_API_VERSION"
	OPENHDC_JUJU_CONTROLLER_ADDRESSES = "OPENHDC_JUJU_CONTROLLER_ADDRESSES"
	OPENHDC_JUJU_USERNAME             = "OPENHDC_JUJU_USERNAME"
	OPENHDC_JUJU_PASSWORD             = "OPENHDC_JUJU_PASSWORD"
	OPENHDC_JUJU_CACERT_PATH          = "OPENHDC_JUJU_CACERT_PATH"
	OPENHDC_HELM_REPOSITORY_URLS      = "OPENHDC_HELM_REPOSITORY_URLS"
	OPENHDC_CHARMHUB_API_URL          = "OPENHDC_CHARMHUB_API_URL"
	OPENHDC_REGISTRY_USERNAME         = "OPENHDC_REGISTRY_USERNAME"
	OPENHDC_REGISTRY_PASSWORD         = "OPENHDC_REGISTRY_UPASSWORD"
)

func GetOrDefault(envVar, defaultValue string) string {
	if value := os.Getenv(envVar); value != "" {
		return value
	}
	return defaultValue
}
