// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/stack/v1/stack.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/openhdc/openhdc/api/stack/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StackServiceName is the fully-qualified name of the StackService service.
	StackServiceName = "openhdc.stack.v1.StackService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StackServiceListNTPServersProcedure is the fully-qualified name of the StackService's
	// ListNTPServers RPC.
	StackServiceListNTPServersProcedure = "/openhdc.stack.v1.StackService/ListNTPServers"
	// StackServiceUpdateNTPServersProcedure is the fully-qualified name of the StackService's
	// UpdateNTPServers RPC.
	StackServiceUpdateNTPServersProcedure = "/openhdc.stack.v1.StackService/UpdateNTPServers"
	// StackServiceListPackageRepositoriesProcedure is the fully-qualified name of the StackService's
	// ListPackageRepositories RPC.
	StackServiceListPackageRepositoriesProcedure = "/openhdc.stack.v1.StackService/ListPackageRepositories"
	// StackServiceUpdatePackageRepositoryURLProcedure is the fully-qualified name of the StackService's
	// UpdatePackageRepositoryURL RPC.
	StackServiceUpdatePackageRepositoryURLProcedure = "/openhdc.stack.v1.StackService/UpdatePackageRepositoryURL"
	// StackServiceListNetworksProcedure is the fully-qualified name of the StackService's ListNetworks
	// RPC.
	StackServiceListNetworksProcedure = "/openhdc.stack.v1.StackService/ListNetworks"
	// StackServiceCreateNetworkProcedure is the fully-qualified name of the StackService's
	// CreateNetwork RPC.
	StackServiceCreateNetworkProcedure = "/openhdc.stack.v1.StackService/CreateNetwork"
	// StackServiceDeleteNetworkProcedure is the fully-qualified name of the StackService's
	// DeleteNetwork RPC.
	StackServiceDeleteNetworkProcedure = "/openhdc.stack.v1.StackService/DeleteNetwork"
	// StackServiceUpdateFabricProcedure is the fully-qualified name of the StackService's UpdateFabric
	// RPC.
	StackServiceUpdateFabricProcedure = "/openhdc.stack.v1.StackService/UpdateFabric"
	// StackServiceUpdateVLANProcedure is the fully-qualified name of the StackService's UpdateVLAN RPC.
	StackServiceUpdateVLANProcedure = "/openhdc.stack.v1.StackService/UpdateVLAN"
	// StackServiceUpdateSubnetProcedure is the fully-qualified name of the StackService's UpdateSubnet
	// RPC.
	StackServiceUpdateSubnetProcedure = "/openhdc.stack.v1.StackService/UpdateSubnet"
	// StackServiceUpdateIPRangeProcedure is the fully-qualified name of the StackService's
	// UpdateIPRange RPC.
	StackServiceUpdateIPRangeProcedure = "/openhdc.stack.v1.StackService/UpdateIPRange"
	// StackServiceListMachinesProcedure is the fully-qualified name of the StackService's ListMachines
	// RPC.
	StackServiceListMachinesProcedure = "/openhdc.stack.v1.StackService/ListMachines"
	// StackServiceGetMachineProcedure is the fully-qualified name of the StackService's GetMachine RPC.
	StackServiceGetMachineProcedure = "/openhdc.stack.v1.StackService/GetMachine"
	// StackServiceAddMachinesProcedure is the fully-qualified name of the StackService's AddMachines
	// RPC.
	StackServiceAddMachinesProcedure = "/openhdc.stack.v1.StackService/AddMachines"
	// StackServiceImportBootResourcesProcedure is the fully-qualified name of the StackService's
	// ImportBootResources RPC.
	StackServiceImportBootResourcesProcedure = "/openhdc.stack.v1.StackService/ImportBootResources"
	// StackServicePowerOnMachineProcedure is the fully-qualified name of the StackService's
	// PowerOnMachine RPC.
	StackServicePowerOnMachineProcedure = "/openhdc.stack.v1.StackService/PowerOnMachine"
	// StackServicePowerOffMachineProcedure is the fully-qualified name of the StackService's
	// PowerOffMachine RPC.
	StackServicePowerOffMachineProcedure = "/openhdc.stack.v1.StackService/PowerOffMachine"
	// StackServiceCommissionMachineProcedure is the fully-qualified name of the StackService's
	// CommissionMachine RPC.
	StackServiceCommissionMachineProcedure = "/openhdc.stack.v1.StackService/CommissionMachine"
	// StackServiceListModelsProcedure is the fully-qualified name of the StackService's ListModels RPC.
	StackServiceListModelsProcedure = "/openhdc.stack.v1.StackService/ListModels"
	// StackServiceCreateModelProcedure is the fully-qualified name of the StackService's CreateModel
	// RPC.
	StackServiceCreateModelProcedure = "/openhdc.stack.v1.StackService/CreateModel"
	// StackServiceGetModelConfigsProcedure is the fully-qualified name of the StackService's
	// GetModelConfigs RPC.
	StackServiceGetModelConfigsProcedure = "/openhdc.stack.v1.StackService/GetModelConfigs"
	// StackServiceListApplicationsProcedure is the fully-qualified name of the StackService's
	// ListApplications RPC.
	StackServiceListApplicationsProcedure = "/openhdc.stack.v1.StackService/ListApplications"
	// StackServiceCreateApplicationProcedure is the fully-qualified name of the StackService's
	// CreateApplication RPC.
	StackServiceCreateApplicationProcedure = "/openhdc.stack.v1.StackService/CreateApplication"
	// StackServiceDeleteApplicationProcedure is the fully-qualified name of the StackService's
	// DeleteApplication RPC.
	StackServiceDeleteApplicationProcedure = "/openhdc.stack.v1.StackService/DeleteApplication"
	// StackServiceUpdateApplicationProcedure is the fully-qualified name of the StackService's
	// UpdateApplication RPC.
	StackServiceUpdateApplicationProcedure = "/openhdc.stack.v1.StackService/UpdateApplication"
	// StackServiceAddApplicationUnitProcedure is the fully-qualified name of the StackService's
	// AddApplicationUnit RPC.
	StackServiceAddApplicationUnitProcedure = "/openhdc.stack.v1.StackService/AddApplicationUnit"
	// StackServiceExposeApplicationProcedure is the fully-qualified name of the StackService's
	// ExposeApplication RPC.
	StackServiceExposeApplicationProcedure = "/openhdc.stack.v1.StackService/ExposeApplication"
	// StackServiceListIntegrationsProcedure is the fully-qualified name of the StackService's
	// ListIntegrations RPC.
	StackServiceListIntegrationsProcedure = "/openhdc.stack.v1.StackService/ListIntegrations"
	// StackServiceCreateIntegrationProcedure is the fully-qualified name of the StackService's
	// CreateIntegration RPC.
	StackServiceCreateIntegrationProcedure = "/openhdc.stack.v1.StackService/CreateIntegration"
	// StackServiceDeleteIntegrationProcedure is the fully-qualified name of the StackService's
	// DeleteIntegration RPC.
	StackServiceDeleteIntegrationProcedure = "/openhdc.stack.v1.StackService/DeleteIntegration"
	// StackServiceListActionsProcedure is the fully-qualified name of the StackService's ListActions
	// RPC.
	StackServiceListActionsProcedure = "/openhdc.stack.v1.StackService/ListActions"
	// StackServiceRunActionProcedure is the fully-qualified name of the StackService's RunAction RPC.
	StackServiceRunActionProcedure = "/openhdc.stack.v1.StackService/RunAction"
)

// StackServiceClient is a client for the openhdc.stack.v1.StackService service.
type StackServiceClient interface {
	// Global Configurations
	ListNTPServers(context.Context, *connect.Request[v1.ListNTPServersRequest]) (*connect.Response[v1.ListNTPServersResponse], error)
	UpdateNTPServers(context.Context, *connect.Request[v1.UpdateNTPServersRequest]) (*connect.Response[emptypb.Empty], error)
	// Package Repository Management
	ListPackageRepositories(context.Context, *connect.Request[v1.ListPackageRepositoriesRequest]) (*connect.Response[v1.ListPackageRepositoriesResponse], error)
	UpdatePackageRepositoryURL(context.Context, *connect.Request[v1.UpdatePackageRepositoryURLRequest]) (*connect.Response[v1.PackageRepository], error)
	// Network Management
	ListNetworks(context.Context, *connect.Request[v1.ListNetworksRequest]) (*connect.Response[v1.ListNetworksResponse], error)
	CreateNetwork(context.Context, *connect.Request[v1.CreateNetworkRequest]) (*connect.Response[v1.Network], error)
	DeleteNetwork(context.Context, *connect.Request[v1.DeleteNetworkRequest]) (*connect.Response[emptypb.Empty], error)
	UpdateFabric(context.Context, *connect.Request[v1.UpdateFabricRequest]) (*connect.Response[v1.Fabric], error)
	UpdateVLAN(context.Context, *connect.Request[v1.UpdateVLANRequest]) (*connect.Response[v1.VLAN], error)
	UpdateSubnet(context.Context, *connect.Request[v1.UpdateSubnetRequest]) (*connect.Response[v1.Subnet], error)
	UpdateIPRange(context.Context, *connect.Request[v1.UpdateIPRangeRequest]) (*connect.Response[v1.IPRange], error)
	// Machine Management
	ListMachines(context.Context, *connect.Request[v1.ListMachinesRequest]) (*connect.Response[v1.ListMachinesResponse], error)
	GetMachine(context.Context, *connect.Request[v1.GetMachineRequest]) (*connect.Response[v1.Machine], error)
	AddMachines(context.Context, *connect.Request[v1.AddMachinesRequest]) (*connect.Response[v1.AddMachinesResponse], error)
	// Machine Operations
	ImportBootResources(context.Context, *connect.Request[v1.ImportBootResourcesRequest]) (*connect.Response[emptypb.Empty], error)
	PowerOnMachine(context.Context, *connect.Request[v1.PowerOnMachineRequest]) (*connect.Response[v1.Machine], error)
	PowerOffMachine(context.Context, *connect.Request[v1.PowerOffMachineRequest]) (*connect.Response[v1.Machine], error)
	CommissionMachine(context.Context, *connect.Request[v1.CommissionMachineRequest]) (*connect.Response[v1.Machine], error)
	// Model Operations
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	CreateModel(context.Context, *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.Model], error)
	GetModelConfigs(context.Context, *connect.Request[v1.GetModelConfigsRequest]) (*connect.Response[v1.GetModelConfigsResponse], error)
	// Application Operations
	ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error)
	CreateApplication(context.Context, *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.Application], error)
	DeleteApplication(context.Context, *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[emptypb.Empty], error)
	UpdateApplication(context.Context, *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.Application], error)
	AddApplicationUnit(context.Context, *connect.Request[v1.AddApplicationUnitRequest]) (*connect.Response[v1.Application], error)
	ExposeApplication(context.Context, *connect.Request[v1.ExposeApplicationRequest]) (*connect.Response[v1.Application], error)
	// Integration Operations
	ListIntegrations(context.Context, *connect.Request[v1.ListIntegrationsRequest]) (*connect.Response[v1.ListIntegrationsResponse], error)
	CreateIntegration(context.Context, *connect.Request[v1.CreateIntegrationRequest]) (*connect.Response[v1.Integration], error)
	DeleteIntegration(context.Context, *connect.Request[v1.DeleteIntegrationRequest]) (*connect.Response[emptypb.Empty], error)
	// Action Operations
	ListActions(context.Context, *connect.Request[v1.ListActionsRequest]) (*connect.Response[v1.ListActionsResponse], error)
	RunAction(context.Context, *connect.Request[v1.RunActionRequest]) (*connect.Response[v1.Action], error)
}

// NewStackServiceClient constructs a client for the openhdc.stack.v1.StackService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStackServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StackServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	stackServiceMethods := v1.File_api_stack_v1_stack_proto.Services().ByName("StackService").Methods()
	return &stackServiceClient{
		listNTPServers: connect.NewClient[v1.ListNTPServersRequest, v1.ListNTPServersResponse](
			httpClient,
			baseURL+StackServiceListNTPServersProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ListNTPServers")),
			connect.WithClientOptions(opts...),
		),
		updateNTPServers: connect.NewClient[v1.UpdateNTPServersRequest, emptypb.Empty](
			httpClient,
			baseURL+StackServiceUpdateNTPServersProcedure,
			connect.WithSchema(stackServiceMethods.ByName("UpdateNTPServers")),
			connect.WithClientOptions(opts...),
		),
		listPackageRepositories: connect.NewClient[v1.ListPackageRepositoriesRequest, v1.ListPackageRepositoriesResponse](
			httpClient,
			baseURL+StackServiceListPackageRepositoriesProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ListPackageRepositories")),
			connect.WithClientOptions(opts...),
		),
		updatePackageRepositoryURL: connect.NewClient[v1.UpdatePackageRepositoryURLRequest, v1.PackageRepository](
			httpClient,
			baseURL+StackServiceUpdatePackageRepositoryURLProcedure,
			connect.WithSchema(stackServiceMethods.ByName("UpdatePackageRepositoryURL")),
			connect.WithClientOptions(opts...),
		),
		listNetworks: connect.NewClient[v1.ListNetworksRequest, v1.ListNetworksResponse](
			httpClient,
			baseURL+StackServiceListNetworksProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ListNetworks")),
			connect.WithClientOptions(opts...),
		),
		createNetwork: connect.NewClient[v1.CreateNetworkRequest, v1.Network](
			httpClient,
			baseURL+StackServiceCreateNetworkProcedure,
			connect.WithSchema(stackServiceMethods.ByName("CreateNetwork")),
			connect.WithClientOptions(opts...),
		),
		deleteNetwork: connect.NewClient[v1.DeleteNetworkRequest, emptypb.Empty](
			httpClient,
			baseURL+StackServiceDeleteNetworkProcedure,
			connect.WithSchema(stackServiceMethods.ByName("DeleteNetwork")),
			connect.WithClientOptions(opts...),
		),
		updateFabric: connect.NewClient[v1.UpdateFabricRequest, v1.Fabric](
			httpClient,
			baseURL+StackServiceUpdateFabricProcedure,
			connect.WithSchema(stackServiceMethods.ByName("UpdateFabric")),
			connect.WithClientOptions(opts...),
		),
		updateVLAN: connect.NewClient[v1.UpdateVLANRequest, v1.VLAN](
			httpClient,
			baseURL+StackServiceUpdateVLANProcedure,
			connect.WithSchema(stackServiceMethods.ByName("UpdateVLAN")),
			connect.WithClientOptions(opts...),
		),
		updateSubnet: connect.NewClient[v1.UpdateSubnetRequest, v1.Subnet](
			httpClient,
			baseURL+StackServiceUpdateSubnetProcedure,
			connect.WithSchema(stackServiceMethods.ByName("UpdateSubnet")),
			connect.WithClientOptions(opts...),
		),
		updateIPRange: connect.NewClient[v1.UpdateIPRangeRequest, v1.IPRange](
			httpClient,
			baseURL+StackServiceUpdateIPRangeProcedure,
			connect.WithSchema(stackServiceMethods.ByName("UpdateIPRange")),
			connect.WithClientOptions(opts...),
		),
		listMachines: connect.NewClient[v1.ListMachinesRequest, v1.ListMachinesResponse](
			httpClient,
			baseURL+StackServiceListMachinesProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ListMachines")),
			connect.WithClientOptions(opts...),
		),
		getMachine: connect.NewClient[v1.GetMachineRequest, v1.Machine](
			httpClient,
			baseURL+StackServiceGetMachineProcedure,
			connect.WithSchema(stackServiceMethods.ByName("GetMachine")),
			connect.WithClientOptions(opts...),
		),
		addMachines: connect.NewClient[v1.AddMachinesRequest, v1.AddMachinesResponse](
			httpClient,
			baseURL+StackServiceAddMachinesProcedure,
			connect.WithSchema(stackServiceMethods.ByName("AddMachines")),
			connect.WithClientOptions(opts...),
		),
		importBootResources: connect.NewClient[v1.ImportBootResourcesRequest, emptypb.Empty](
			httpClient,
			baseURL+StackServiceImportBootResourcesProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ImportBootResources")),
			connect.WithClientOptions(opts...),
		),
		powerOnMachine: connect.NewClient[v1.PowerOnMachineRequest, v1.Machine](
			httpClient,
			baseURL+StackServicePowerOnMachineProcedure,
			connect.WithSchema(stackServiceMethods.ByName("PowerOnMachine")),
			connect.WithClientOptions(opts...),
		),
		powerOffMachine: connect.NewClient[v1.PowerOffMachineRequest, v1.Machine](
			httpClient,
			baseURL+StackServicePowerOffMachineProcedure,
			connect.WithSchema(stackServiceMethods.ByName("PowerOffMachine")),
			connect.WithClientOptions(opts...),
		),
		commissionMachine: connect.NewClient[v1.CommissionMachineRequest, v1.Machine](
			httpClient,
			baseURL+StackServiceCommissionMachineProcedure,
			connect.WithSchema(stackServiceMethods.ByName("CommissionMachine")),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+StackServiceListModelsProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		createModel: connect.NewClient[v1.CreateModelRequest, v1.Model](
			httpClient,
			baseURL+StackServiceCreateModelProcedure,
			connect.WithSchema(stackServiceMethods.ByName("CreateModel")),
			connect.WithClientOptions(opts...),
		),
		getModelConfigs: connect.NewClient[v1.GetModelConfigsRequest, v1.GetModelConfigsResponse](
			httpClient,
			baseURL+StackServiceGetModelConfigsProcedure,
			connect.WithSchema(stackServiceMethods.ByName("GetModelConfigs")),
			connect.WithClientOptions(opts...),
		),
		listApplications: connect.NewClient[v1.ListApplicationsRequest, v1.ListApplicationsResponse](
			httpClient,
			baseURL+StackServiceListApplicationsProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ListApplications")),
			connect.WithClientOptions(opts...),
		),
		createApplication: connect.NewClient[v1.CreateApplicationRequest, v1.Application](
			httpClient,
			baseURL+StackServiceCreateApplicationProcedure,
			connect.WithSchema(stackServiceMethods.ByName("CreateApplication")),
			connect.WithClientOptions(opts...),
		),
		deleteApplication: connect.NewClient[v1.DeleteApplicationRequest, emptypb.Empty](
			httpClient,
			baseURL+StackServiceDeleteApplicationProcedure,
			connect.WithSchema(stackServiceMethods.ByName("DeleteApplication")),
			connect.WithClientOptions(opts...),
		),
		updateApplication: connect.NewClient[v1.UpdateApplicationRequest, v1.Application](
			httpClient,
			baseURL+StackServiceUpdateApplicationProcedure,
			connect.WithSchema(stackServiceMethods.ByName("UpdateApplication")),
			connect.WithClientOptions(opts...),
		),
		addApplicationUnit: connect.NewClient[v1.AddApplicationUnitRequest, v1.Application](
			httpClient,
			baseURL+StackServiceAddApplicationUnitProcedure,
			connect.WithSchema(stackServiceMethods.ByName("AddApplicationUnit")),
			connect.WithClientOptions(opts...),
		),
		exposeApplication: connect.NewClient[v1.ExposeApplicationRequest, v1.Application](
			httpClient,
			baseURL+StackServiceExposeApplicationProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ExposeApplication")),
			connect.WithClientOptions(opts...),
		),
		listIntegrations: connect.NewClient[v1.ListIntegrationsRequest, v1.ListIntegrationsResponse](
			httpClient,
			baseURL+StackServiceListIntegrationsProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ListIntegrations")),
			connect.WithClientOptions(opts...),
		),
		createIntegration: connect.NewClient[v1.CreateIntegrationRequest, v1.Integration](
			httpClient,
			baseURL+StackServiceCreateIntegrationProcedure,
			connect.WithSchema(stackServiceMethods.ByName("CreateIntegration")),
			connect.WithClientOptions(opts...),
		),
		deleteIntegration: connect.NewClient[v1.DeleteIntegrationRequest, emptypb.Empty](
			httpClient,
			baseURL+StackServiceDeleteIntegrationProcedure,
			connect.WithSchema(stackServiceMethods.ByName("DeleteIntegration")),
			connect.WithClientOptions(opts...),
		),
		listActions: connect.NewClient[v1.ListActionsRequest, v1.ListActionsResponse](
			httpClient,
			baseURL+StackServiceListActionsProcedure,
			connect.WithSchema(stackServiceMethods.ByName("ListActions")),
			connect.WithClientOptions(opts...),
		),
		runAction: connect.NewClient[v1.RunActionRequest, v1.Action](
			httpClient,
			baseURL+StackServiceRunActionProcedure,
			connect.WithSchema(stackServiceMethods.ByName("RunAction")),
			connect.WithClientOptions(opts...),
		),
	}
}

// stackServiceClient implements StackServiceClient.
type stackServiceClient struct {
	listNTPServers             *connect.Client[v1.ListNTPServersRequest, v1.ListNTPServersResponse]
	updateNTPServers           *connect.Client[v1.UpdateNTPServersRequest, emptypb.Empty]
	listPackageRepositories    *connect.Client[v1.ListPackageRepositoriesRequest, v1.ListPackageRepositoriesResponse]
	updatePackageRepositoryURL *connect.Client[v1.UpdatePackageRepositoryURLRequest, v1.PackageRepository]
	listNetworks               *connect.Client[v1.ListNetworksRequest, v1.ListNetworksResponse]
	createNetwork              *connect.Client[v1.CreateNetworkRequest, v1.Network]
	deleteNetwork              *connect.Client[v1.DeleteNetworkRequest, emptypb.Empty]
	updateFabric               *connect.Client[v1.UpdateFabricRequest, v1.Fabric]
	updateVLAN                 *connect.Client[v1.UpdateVLANRequest, v1.VLAN]
	updateSubnet               *connect.Client[v1.UpdateSubnetRequest, v1.Subnet]
	updateIPRange              *connect.Client[v1.UpdateIPRangeRequest, v1.IPRange]
	listMachines               *connect.Client[v1.ListMachinesRequest, v1.ListMachinesResponse]
	getMachine                 *connect.Client[v1.GetMachineRequest, v1.Machine]
	addMachines                *connect.Client[v1.AddMachinesRequest, v1.AddMachinesResponse]
	importBootResources        *connect.Client[v1.ImportBootResourcesRequest, emptypb.Empty]
	powerOnMachine             *connect.Client[v1.PowerOnMachineRequest, v1.Machine]
	powerOffMachine            *connect.Client[v1.PowerOffMachineRequest, v1.Machine]
	commissionMachine          *connect.Client[v1.CommissionMachineRequest, v1.Machine]
	listModels                 *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	createModel                *connect.Client[v1.CreateModelRequest, v1.Model]
	getModelConfigs            *connect.Client[v1.GetModelConfigsRequest, v1.GetModelConfigsResponse]
	listApplications           *connect.Client[v1.ListApplicationsRequest, v1.ListApplicationsResponse]
	createApplication          *connect.Client[v1.CreateApplicationRequest, v1.Application]
	deleteApplication          *connect.Client[v1.DeleteApplicationRequest, emptypb.Empty]
	updateApplication          *connect.Client[v1.UpdateApplicationRequest, v1.Application]
	addApplicationUnit         *connect.Client[v1.AddApplicationUnitRequest, v1.Application]
	exposeApplication          *connect.Client[v1.ExposeApplicationRequest, v1.Application]
	listIntegrations           *connect.Client[v1.ListIntegrationsRequest, v1.ListIntegrationsResponse]
	createIntegration          *connect.Client[v1.CreateIntegrationRequest, v1.Integration]
	deleteIntegration          *connect.Client[v1.DeleteIntegrationRequest, emptypb.Empty]
	listActions                *connect.Client[v1.ListActionsRequest, v1.ListActionsResponse]
	runAction                  *connect.Client[v1.RunActionRequest, v1.Action]
}

// ListNTPServers calls openhdc.stack.v1.StackService.ListNTPServers.
func (c *stackServiceClient) ListNTPServers(ctx context.Context, req *connect.Request[v1.ListNTPServersRequest]) (*connect.Response[v1.ListNTPServersResponse], error) {
	return c.listNTPServers.CallUnary(ctx, req)
}

// UpdateNTPServers calls openhdc.stack.v1.StackService.UpdateNTPServers.
func (c *stackServiceClient) UpdateNTPServers(ctx context.Context, req *connect.Request[v1.UpdateNTPServersRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.updateNTPServers.CallUnary(ctx, req)
}

// ListPackageRepositories calls openhdc.stack.v1.StackService.ListPackageRepositories.
func (c *stackServiceClient) ListPackageRepositories(ctx context.Context, req *connect.Request[v1.ListPackageRepositoriesRequest]) (*connect.Response[v1.ListPackageRepositoriesResponse], error) {
	return c.listPackageRepositories.CallUnary(ctx, req)
}

// UpdatePackageRepositoryURL calls openhdc.stack.v1.StackService.UpdatePackageRepositoryURL.
func (c *stackServiceClient) UpdatePackageRepositoryURL(ctx context.Context, req *connect.Request[v1.UpdatePackageRepositoryURLRequest]) (*connect.Response[v1.PackageRepository], error) {
	return c.updatePackageRepositoryURL.CallUnary(ctx, req)
}

// ListNetworks calls openhdc.stack.v1.StackService.ListNetworks.
func (c *stackServiceClient) ListNetworks(ctx context.Context, req *connect.Request[v1.ListNetworksRequest]) (*connect.Response[v1.ListNetworksResponse], error) {
	return c.listNetworks.CallUnary(ctx, req)
}

// CreateNetwork calls openhdc.stack.v1.StackService.CreateNetwork.
func (c *stackServiceClient) CreateNetwork(ctx context.Context, req *connect.Request[v1.CreateNetworkRequest]) (*connect.Response[v1.Network], error) {
	return c.createNetwork.CallUnary(ctx, req)
}

// DeleteNetwork calls openhdc.stack.v1.StackService.DeleteNetwork.
func (c *stackServiceClient) DeleteNetwork(ctx context.Context, req *connect.Request[v1.DeleteNetworkRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteNetwork.CallUnary(ctx, req)
}

// UpdateFabric calls openhdc.stack.v1.StackService.UpdateFabric.
func (c *stackServiceClient) UpdateFabric(ctx context.Context, req *connect.Request[v1.UpdateFabricRequest]) (*connect.Response[v1.Fabric], error) {
	return c.updateFabric.CallUnary(ctx, req)
}

// UpdateVLAN calls openhdc.stack.v1.StackService.UpdateVLAN.
func (c *stackServiceClient) UpdateVLAN(ctx context.Context, req *connect.Request[v1.UpdateVLANRequest]) (*connect.Response[v1.VLAN], error) {
	return c.updateVLAN.CallUnary(ctx, req)
}

// UpdateSubnet calls openhdc.stack.v1.StackService.UpdateSubnet.
func (c *stackServiceClient) UpdateSubnet(ctx context.Context, req *connect.Request[v1.UpdateSubnetRequest]) (*connect.Response[v1.Subnet], error) {
	return c.updateSubnet.CallUnary(ctx, req)
}

// UpdateIPRange calls openhdc.stack.v1.StackService.UpdateIPRange.
func (c *stackServiceClient) UpdateIPRange(ctx context.Context, req *connect.Request[v1.UpdateIPRangeRequest]) (*connect.Response[v1.IPRange], error) {
	return c.updateIPRange.CallUnary(ctx, req)
}

// ListMachines calls openhdc.stack.v1.StackService.ListMachines.
func (c *stackServiceClient) ListMachines(ctx context.Context, req *connect.Request[v1.ListMachinesRequest]) (*connect.Response[v1.ListMachinesResponse], error) {
	return c.listMachines.CallUnary(ctx, req)
}

// GetMachine calls openhdc.stack.v1.StackService.GetMachine.
func (c *stackServiceClient) GetMachine(ctx context.Context, req *connect.Request[v1.GetMachineRequest]) (*connect.Response[v1.Machine], error) {
	return c.getMachine.CallUnary(ctx, req)
}

// AddMachines calls openhdc.stack.v1.StackService.AddMachines.
func (c *stackServiceClient) AddMachines(ctx context.Context, req *connect.Request[v1.AddMachinesRequest]) (*connect.Response[v1.AddMachinesResponse], error) {
	return c.addMachines.CallUnary(ctx, req)
}

// ImportBootResources calls openhdc.stack.v1.StackService.ImportBootResources.
func (c *stackServiceClient) ImportBootResources(ctx context.Context, req *connect.Request[v1.ImportBootResourcesRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.importBootResources.CallUnary(ctx, req)
}

// PowerOnMachine calls openhdc.stack.v1.StackService.PowerOnMachine.
func (c *stackServiceClient) PowerOnMachine(ctx context.Context, req *connect.Request[v1.PowerOnMachineRequest]) (*connect.Response[v1.Machine], error) {
	return c.powerOnMachine.CallUnary(ctx, req)
}

// PowerOffMachine calls openhdc.stack.v1.StackService.PowerOffMachine.
func (c *stackServiceClient) PowerOffMachine(ctx context.Context, req *connect.Request[v1.PowerOffMachineRequest]) (*connect.Response[v1.Machine], error) {
	return c.powerOffMachine.CallUnary(ctx, req)
}

// CommissionMachine calls openhdc.stack.v1.StackService.CommissionMachine.
func (c *stackServiceClient) CommissionMachine(ctx context.Context, req *connect.Request[v1.CommissionMachineRequest]) (*connect.Response[v1.Machine], error) {
	return c.commissionMachine.CallUnary(ctx, req)
}

// ListModels calls openhdc.stack.v1.StackService.ListModels.
func (c *stackServiceClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// CreateModel calls openhdc.stack.v1.StackService.CreateModel.
func (c *stackServiceClient) CreateModel(ctx context.Context, req *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.Model], error) {
	return c.createModel.CallUnary(ctx, req)
}

// GetModelConfigs calls openhdc.stack.v1.StackService.GetModelConfigs.
func (c *stackServiceClient) GetModelConfigs(ctx context.Context, req *connect.Request[v1.GetModelConfigsRequest]) (*connect.Response[v1.GetModelConfigsResponse], error) {
	return c.getModelConfigs.CallUnary(ctx, req)
}

// ListApplications calls openhdc.stack.v1.StackService.ListApplications.
func (c *stackServiceClient) ListApplications(ctx context.Context, req *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error) {
	return c.listApplications.CallUnary(ctx, req)
}

// CreateApplication calls openhdc.stack.v1.StackService.CreateApplication.
func (c *stackServiceClient) CreateApplication(ctx context.Context, req *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.Application], error) {
	return c.createApplication.CallUnary(ctx, req)
}

// DeleteApplication calls openhdc.stack.v1.StackService.DeleteApplication.
func (c *stackServiceClient) DeleteApplication(ctx context.Context, req *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteApplication.CallUnary(ctx, req)
}

// UpdateApplication calls openhdc.stack.v1.StackService.UpdateApplication.
func (c *stackServiceClient) UpdateApplication(ctx context.Context, req *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.Application], error) {
	return c.updateApplication.CallUnary(ctx, req)
}

// AddApplicationUnit calls openhdc.stack.v1.StackService.AddApplicationUnit.
func (c *stackServiceClient) AddApplicationUnit(ctx context.Context, req *connect.Request[v1.AddApplicationUnitRequest]) (*connect.Response[v1.Application], error) {
	return c.addApplicationUnit.CallUnary(ctx, req)
}

// ExposeApplication calls openhdc.stack.v1.StackService.ExposeApplication.
func (c *stackServiceClient) ExposeApplication(ctx context.Context, req *connect.Request[v1.ExposeApplicationRequest]) (*connect.Response[v1.Application], error) {
	return c.exposeApplication.CallUnary(ctx, req)
}

// ListIntegrations calls openhdc.stack.v1.StackService.ListIntegrations.
func (c *stackServiceClient) ListIntegrations(ctx context.Context, req *connect.Request[v1.ListIntegrationsRequest]) (*connect.Response[v1.ListIntegrationsResponse], error) {
	return c.listIntegrations.CallUnary(ctx, req)
}

// CreateIntegration calls openhdc.stack.v1.StackService.CreateIntegration.
func (c *stackServiceClient) CreateIntegration(ctx context.Context, req *connect.Request[v1.CreateIntegrationRequest]) (*connect.Response[v1.Integration], error) {
	return c.createIntegration.CallUnary(ctx, req)
}

// DeleteIntegration calls openhdc.stack.v1.StackService.DeleteIntegration.
func (c *stackServiceClient) DeleteIntegration(ctx context.Context, req *connect.Request[v1.DeleteIntegrationRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteIntegration.CallUnary(ctx, req)
}

// ListActions calls openhdc.stack.v1.StackService.ListActions.
func (c *stackServiceClient) ListActions(ctx context.Context, req *connect.Request[v1.ListActionsRequest]) (*connect.Response[v1.ListActionsResponse], error) {
	return c.listActions.CallUnary(ctx, req)
}

// RunAction calls openhdc.stack.v1.StackService.RunAction.
func (c *stackServiceClient) RunAction(ctx context.Context, req *connect.Request[v1.RunActionRequest]) (*connect.Response[v1.Action], error) {
	return c.runAction.CallUnary(ctx, req)
}

// StackServiceHandler is an implementation of the openhdc.stack.v1.StackService service.
type StackServiceHandler interface {
	// Global Configurations
	ListNTPServers(context.Context, *connect.Request[v1.ListNTPServersRequest]) (*connect.Response[v1.ListNTPServersResponse], error)
	UpdateNTPServers(context.Context, *connect.Request[v1.UpdateNTPServersRequest]) (*connect.Response[emptypb.Empty], error)
	// Package Repository Management
	ListPackageRepositories(context.Context, *connect.Request[v1.ListPackageRepositoriesRequest]) (*connect.Response[v1.ListPackageRepositoriesResponse], error)
	UpdatePackageRepositoryURL(context.Context, *connect.Request[v1.UpdatePackageRepositoryURLRequest]) (*connect.Response[v1.PackageRepository], error)
	// Network Management
	ListNetworks(context.Context, *connect.Request[v1.ListNetworksRequest]) (*connect.Response[v1.ListNetworksResponse], error)
	CreateNetwork(context.Context, *connect.Request[v1.CreateNetworkRequest]) (*connect.Response[v1.Network], error)
	DeleteNetwork(context.Context, *connect.Request[v1.DeleteNetworkRequest]) (*connect.Response[emptypb.Empty], error)
	UpdateFabric(context.Context, *connect.Request[v1.UpdateFabricRequest]) (*connect.Response[v1.Fabric], error)
	UpdateVLAN(context.Context, *connect.Request[v1.UpdateVLANRequest]) (*connect.Response[v1.VLAN], error)
	UpdateSubnet(context.Context, *connect.Request[v1.UpdateSubnetRequest]) (*connect.Response[v1.Subnet], error)
	UpdateIPRange(context.Context, *connect.Request[v1.UpdateIPRangeRequest]) (*connect.Response[v1.IPRange], error)
	// Machine Management
	ListMachines(context.Context, *connect.Request[v1.ListMachinesRequest]) (*connect.Response[v1.ListMachinesResponse], error)
	GetMachine(context.Context, *connect.Request[v1.GetMachineRequest]) (*connect.Response[v1.Machine], error)
	AddMachines(context.Context, *connect.Request[v1.AddMachinesRequest]) (*connect.Response[v1.AddMachinesResponse], error)
	// Machine Operations
	ImportBootResources(context.Context, *connect.Request[v1.ImportBootResourcesRequest]) (*connect.Response[emptypb.Empty], error)
	PowerOnMachine(context.Context, *connect.Request[v1.PowerOnMachineRequest]) (*connect.Response[v1.Machine], error)
	PowerOffMachine(context.Context, *connect.Request[v1.PowerOffMachineRequest]) (*connect.Response[v1.Machine], error)
	CommissionMachine(context.Context, *connect.Request[v1.CommissionMachineRequest]) (*connect.Response[v1.Machine], error)
	// Model Operations
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	CreateModel(context.Context, *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.Model], error)
	GetModelConfigs(context.Context, *connect.Request[v1.GetModelConfigsRequest]) (*connect.Response[v1.GetModelConfigsResponse], error)
	// Application Operations
	ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error)
	CreateApplication(context.Context, *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.Application], error)
	DeleteApplication(context.Context, *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[emptypb.Empty], error)
	UpdateApplication(context.Context, *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.Application], error)
	AddApplicationUnit(context.Context, *connect.Request[v1.AddApplicationUnitRequest]) (*connect.Response[v1.Application], error)
	ExposeApplication(context.Context, *connect.Request[v1.ExposeApplicationRequest]) (*connect.Response[v1.Application], error)
	// Integration Operations
	ListIntegrations(context.Context, *connect.Request[v1.ListIntegrationsRequest]) (*connect.Response[v1.ListIntegrationsResponse], error)
	CreateIntegration(context.Context, *connect.Request[v1.CreateIntegrationRequest]) (*connect.Response[v1.Integration], error)
	DeleteIntegration(context.Context, *connect.Request[v1.DeleteIntegrationRequest]) (*connect.Response[emptypb.Empty], error)
	// Action Operations
	ListActions(context.Context, *connect.Request[v1.ListActionsRequest]) (*connect.Response[v1.ListActionsResponse], error)
	RunAction(context.Context, *connect.Request[v1.RunActionRequest]) (*connect.Response[v1.Action], error)
}

// NewStackServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStackServiceHandler(svc StackServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	stackServiceMethods := v1.File_api_stack_v1_stack_proto.Services().ByName("StackService").Methods()
	stackServiceListNTPServersHandler := connect.NewUnaryHandler(
		StackServiceListNTPServersProcedure,
		svc.ListNTPServers,
		connect.WithSchema(stackServiceMethods.ByName("ListNTPServers")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceUpdateNTPServersHandler := connect.NewUnaryHandler(
		StackServiceUpdateNTPServersProcedure,
		svc.UpdateNTPServers,
		connect.WithSchema(stackServiceMethods.ByName("UpdateNTPServers")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceListPackageRepositoriesHandler := connect.NewUnaryHandler(
		StackServiceListPackageRepositoriesProcedure,
		svc.ListPackageRepositories,
		connect.WithSchema(stackServiceMethods.ByName("ListPackageRepositories")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceUpdatePackageRepositoryURLHandler := connect.NewUnaryHandler(
		StackServiceUpdatePackageRepositoryURLProcedure,
		svc.UpdatePackageRepositoryURL,
		connect.WithSchema(stackServiceMethods.ByName("UpdatePackageRepositoryURL")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceListNetworksHandler := connect.NewUnaryHandler(
		StackServiceListNetworksProcedure,
		svc.ListNetworks,
		connect.WithSchema(stackServiceMethods.ByName("ListNetworks")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceCreateNetworkHandler := connect.NewUnaryHandler(
		StackServiceCreateNetworkProcedure,
		svc.CreateNetwork,
		connect.WithSchema(stackServiceMethods.ByName("CreateNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceDeleteNetworkHandler := connect.NewUnaryHandler(
		StackServiceDeleteNetworkProcedure,
		svc.DeleteNetwork,
		connect.WithSchema(stackServiceMethods.ByName("DeleteNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceUpdateFabricHandler := connect.NewUnaryHandler(
		StackServiceUpdateFabricProcedure,
		svc.UpdateFabric,
		connect.WithSchema(stackServiceMethods.ByName("UpdateFabric")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceUpdateVLANHandler := connect.NewUnaryHandler(
		StackServiceUpdateVLANProcedure,
		svc.UpdateVLAN,
		connect.WithSchema(stackServiceMethods.ByName("UpdateVLAN")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceUpdateSubnetHandler := connect.NewUnaryHandler(
		StackServiceUpdateSubnetProcedure,
		svc.UpdateSubnet,
		connect.WithSchema(stackServiceMethods.ByName("UpdateSubnet")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceUpdateIPRangeHandler := connect.NewUnaryHandler(
		StackServiceUpdateIPRangeProcedure,
		svc.UpdateIPRange,
		connect.WithSchema(stackServiceMethods.ByName("UpdateIPRange")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceListMachinesHandler := connect.NewUnaryHandler(
		StackServiceListMachinesProcedure,
		svc.ListMachines,
		connect.WithSchema(stackServiceMethods.ByName("ListMachines")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceGetMachineHandler := connect.NewUnaryHandler(
		StackServiceGetMachineProcedure,
		svc.GetMachine,
		connect.WithSchema(stackServiceMethods.ByName("GetMachine")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceAddMachinesHandler := connect.NewUnaryHandler(
		StackServiceAddMachinesProcedure,
		svc.AddMachines,
		connect.WithSchema(stackServiceMethods.ByName("AddMachines")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceImportBootResourcesHandler := connect.NewUnaryHandler(
		StackServiceImportBootResourcesProcedure,
		svc.ImportBootResources,
		connect.WithSchema(stackServiceMethods.ByName("ImportBootResources")),
		connect.WithHandlerOptions(opts...),
	)
	stackServicePowerOnMachineHandler := connect.NewUnaryHandler(
		StackServicePowerOnMachineProcedure,
		svc.PowerOnMachine,
		connect.WithSchema(stackServiceMethods.ByName("PowerOnMachine")),
		connect.WithHandlerOptions(opts...),
	)
	stackServicePowerOffMachineHandler := connect.NewUnaryHandler(
		StackServicePowerOffMachineProcedure,
		svc.PowerOffMachine,
		connect.WithSchema(stackServiceMethods.ByName("PowerOffMachine")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceCommissionMachineHandler := connect.NewUnaryHandler(
		StackServiceCommissionMachineProcedure,
		svc.CommissionMachine,
		connect.WithSchema(stackServiceMethods.ByName("CommissionMachine")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceListModelsHandler := connect.NewUnaryHandler(
		StackServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(stackServiceMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceCreateModelHandler := connect.NewUnaryHandler(
		StackServiceCreateModelProcedure,
		svc.CreateModel,
		connect.WithSchema(stackServiceMethods.ByName("CreateModel")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceGetModelConfigsHandler := connect.NewUnaryHandler(
		StackServiceGetModelConfigsProcedure,
		svc.GetModelConfigs,
		connect.WithSchema(stackServiceMethods.ByName("GetModelConfigs")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceListApplicationsHandler := connect.NewUnaryHandler(
		StackServiceListApplicationsProcedure,
		svc.ListApplications,
		connect.WithSchema(stackServiceMethods.ByName("ListApplications")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceCreateApplicationHandler := connect.NewUnaryHandler(
		StackServiceCreateApplicationProcedure,
		svc.CreateApplication,
		connect.WithSchema(stackServiceMethods.ByName("CreateApplication")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceDeleteApplicationHandler := connect.NewUnaryHandler(
		StackServiceDeleteApplicationProcedure,
		svc.DeleteApplication,
		connect.WithSchema(stackServiceMethods.ByName("DeleteApplication")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceUpdateApplicationHandler := connect.NewUnaryHandler(
		StackServiceUpdateApplicationProcedure,
		svc.UpdateApplication,
		connect.WithSchema(stackServiceMethods.ByName("UpdateApplication")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceAddApplicationUnitHandler := connect.NewUnaryHandler(
		StackServiceAddApplicationUnitProcedure,
		svc.AddApplicationUnit,
		connect.WithSchema(stackServiceMethods.ByName("AddApplicationUnit")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceExposeApplicationHandler := connect.NewUnaryHandler(
		StackServiceExposeApplicationProcedure,
		svc.ExposeApplication,
		connect.WithSchema(stackServiceMethods.ByName("ExposeApplication")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceListIntegrationsHandler := connect.NewUnaryHandler(
		StackServiceListIntegrationsProcedure,
		svc.ListIntegrations,
		connect.WithSchema(stackServiceMethods.ByName("ListIntegrations")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceCreateIntegrationHandler := connect.NewUnaryHandler(
		StackServiceCreateIntegrationProcedure,
		svc.CreateIntegration,
		connect.WithSchema(stackServiceMethods.ByName("CreateIntegration")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceDeleteIntegrationHandler := connect.NewUnaryHandler(
		StackServiceDeleteIntegrationProcedure,
		svc.DeleteIntegration,
		connect.WithSchema(stackServiceMethods.ByName("DeleteIntegration")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceListActionsHandler := connect.NewUnaryHandler(
		StackServiceListActionsProcedure,
		svc.ListActions,
		connect.WithSchema(stackServiceMethods.ByName("ListActions")),
		connect.WithHandlerOptions(opts...),
	)
	stackServiceRunActionHandler := connect.NewUnaryHandler(
		StackServiceRunActionProcedure,
		svc.RunAction,
		connect.WithSchema(stackServiceMethods.ByName("RunAction")),
		connect.WithHandlerOptions(opts...),
	)
	return "/openhdc.stack.v1.StackService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StackServiceListNTPServersProcedure:
			stackServiceListNTPServersHandler.ServeHTTP(w, r)
		case StackServiceUpdateNTPServersProcedure:
			stackServiceUpdateNTPServersHandler.ServeHTTP(w, r)
		case StackServiceListPackageRepositoriesProcedure:
			stackServiceListPackageRepositoriesHandler.ServeHTTP(w, r)
		case StackServiceUpdatePackageRepositoryURLProcedure:
			stackServiceUpdatePackageRepositoryURLHandler.ServeHTTP(w, r)
		case StackServiceListNetworksProcedure:
			stackServiceListNetworksHandler.ServeHTTP(w, r)
		case StackServiceCreateNetworkProcedure:
			stackServiceCreateNetworkHandler.ServeHTTP(w, r)
		case StackServiceDeleteNetworkProcedure:
			stackServiceDeleteNetworkHandler.ServeHTTP(w, r)
		case StackServiceUpdateFabricProcedure:
			stackServiceUpdateFabricHandler.ServeHTTP(w, r)
		case StackServiceUpdateVLANProcedure:
			stackServiceUpdateVLANHandler.ServeHTTP(w, r)
		case StackServiceUpdateSubnetProcedure:
			stackServiceUpdateSubnetHandler.ServeHTTP(w, r)
		case StackServiceUpdateIPRangeProcedure:
			stackServiceUpdateIPRangeHandler.ServeHTTP(w, r)
		case StackServiceListMachinesProcedure:
			stackServiceListMachinesHandler.ServeHTTP(w, r)
		case StackServiceGetMachineProcedure:
			stackServiceGetMachineHandler.ServeHTTP(w, r)
		case StackServiceAddMachinesProcedure:
			stackServiceAddMachinesHandler.ServeHTTP(w, r)
		case StackServiceImportBootResourcesProcedure:
			stackServiceImportBootResourcesHandler.ServeHTTP(w, r)
		case StackServicePowerOnMachineProcedure:
			stackServicePowerOnMachineHandler.ServeHTTP(w, r)
		case StackServicePowerOffMachineProcedure:
			stackServicePowerOffMachineHandler.ServeHTTP(w, r)
		case StackServiceCommissionMachineProcedure:
			stackServiceCommissionMachineHandler.ServeHTTP(w, r)
		case StackServiceListModelsProcedure:
			stackServiceListModelsHandler.ServeHTTP(w, r)
		case StackServiceCreateModelProcedure:
			stackServiceCreateModelHandler.ServeHTTP(w, r)
		case StackServiceGetModelConfigsProcedure:
			stackServiceGetModelConfigsHandler.ServeHTTP(w, r)
		case StackServiceListApplicationsProcedure:
			stackServiceListApplicationsHandler.ServeHTTP(w, r)
		case StackServiceCreateApplicationProcedure:
			stackServiceCreateApplicationHandler.ServeHTTP(w, r)
		case StackServiceDeleteApplicationProcedure:
			stackServiceDeleteApplicationHandler.ServeHTTP(w, r)
		case StackServiceUpdateApplicationProcedure:
			stackServiceUpdateApplicationHandler.ServeHTTP(w, r)
		case StackServiceAddApplicationUnitProcedure:
			stackServiceAddApplicationUnitHandler.ServeHTTP(w, r)
		case StackServiceExposeApplicationProcedure:
			stackServiceExposeApplicationHandler.ServeHTTP(w, r)
		case StackServiceListIntegrationsProcedure:
			stackServiceListIntegrationsHandler.ServeHTTP(w, r)
		case StackServiceCreateIntegrationProcedure:
			stackServiceCreateIntegrationHandler.ServeHTTP(w, r)
		case StackServiceDeleteIntegrationProcedure:
			stackServiceDeleteIntegrationHandler.ServeHTTP(w, r)
		case StackServiceListActionsProcedure:
			stackServiceListActionsHandler.ServeHTTP(w, r)
		case StackServiceRunActionProcedure:
			stackServiceRunActionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStackServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStackServiceHandler struct{}

func (UnimplementedStackServiceHandler) ListNTPServers(context.Context, *connect.Request[v1.ListNTPServersRequest]) (*connect.Response[v1.ListNTPServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ListNTPServers is not implemented"))
}

func (UnimplementedStackServiceHandler) UpdateNTPServers(context.Context, *connect.Request[v1.UpdateNTPServersRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.UpdateNTPServers is not implemented"))
}

func (UnimplementedStackServiceHandler) ListPackageRepositories(context.Context, *connect.Request[v1.ListPackageRepositoriesRequest]) (*connect.Response[v1.ListPackageRepositoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ListPackageRepositories is not implemented"))
}

func (UnimplementedStackServiceHandler) UpdatePackageRepositoryURL(context.Context, *connect.Request[v1.UpdatePackageRepositoryURLRequest]) (*connect.Response[v1.PackageRepository], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.UpdatePackageRepositoryURL is not implemented"))
}

func (UnimplementedStackServiceHandler) ListNetworks(context.Context, *connect.Request[v1.ListNetworksRequest]) (*connect.Response[v1.ListNetworksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ListNetworks is not implemented"))
}

func (UnimplementedStackServiceHandler) CreateNetwork(context.Context, *connect.Request[v1.CreateNetworkRequest]) (*connect.Response[v1.Network], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.CreateNetwork is not implemented"))
}

func (UnimplementedStackServiceHandler) DeleteNetwork(context.Context, *connect.Request[v1.DeleteNetworkRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.DeleteNetwork is not implemented"))
}

func (UnimplementedStackServiceHandler) UpdateFabric(context.Context, *connect.Request[v1.UpdateFabricRequest]) (*connect.Response[v1.Fabric], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.UpdateFabric is not implemented"))
}

func (UnimplementedStackServiceHandler) UpdateVLAN(context.Context, *connect.Request[v1.UpdateVLANRequest]) (*connect.Response[v1.VLAN], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.UpdateVLAN is not implemented"))
}

func (UnimplementedStackServiceHandler) UpdateSubnet(context.Context, *connect.Request[v1.UpdateSubnetRequest]) (*connect.Response[v1.Subnet], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.UpdateSubnet is not implemented"))
}

func (UnimplementedStackServiceHandler) UpdateIPRange(context.Context, *connect.Request[v1.UpdateIPRangeRequest]) (*connect.Response[v1.IPRange], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.UpdateIPRange is not implemented"))
}

func (UnimplementedStackServiceHandler) ListMachines(context.Context, *connect.Request[v1.ListMachinesRequest]) (*connect.Response[v1.ListMachinesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ListMachines is not implemented"))
}

func (UnimplementedStackServiceHandler) GetMachine(context.Context, *connect.Request[v1.GetMachineRequest]) (*connect.Response[v1.Machine], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.GetMachine is not implemented"))
}

func (UnimplementedStackServiceHandler) AddMachines(context.Context, *connect.Request[v1.AddMachinesRequest]) (*connect.Response[v1.AddMachinesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.AddMachines is not implemented"))
}

func (UnimplementedStackServiceHandler) ImportBootResources(context.Context, *connect.Request[v1.ImportBootResourcesRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ImportBootResources is not implemented"))
}

func (UnimplementedStackServiceHandler) PowerOnMachine(context.Context, *connect.Request[v1.PowerOnMachineRequest]) (*connect.Response[v1.Machine], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.PowerOnMachine is not implemented"))
}

func (UnimplementedStackServiceHandler) PowerOffMachine(context.Context, *connect.Request[v1.PowerOffMachineRequest]) (*connect.Response[v1.Machine], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.PowerOffMachine is not implemented"))
}

func (UnimplementedStackServiceHandler) CommissionMachine(context.Context, *connect.Request[v1.CommissionMachineRequest]) (*connect.Response[v1.Machine], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.CommissionMachine is not implemented"))
}

func (UnimplementedStackServiceHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ListModels is not implemented"))
}

func (UnimplementedStackServiceHandler) CreateModel(context.Context, *connect.Request[v1.CreateModelRequest]) (*connect.Response[v1.Model], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.CreateModel is not implemented"))
}

func (UnimplementedStackServiceHandler) GetModelConfigs(context.Context, *connect.Request[v1.GetModelConfigsRequest]) (*connect.Response[v1.GetModelConfigsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.GetModelConfigs is not implemented"))
}

func (UnimplementedStackServiceHandler) ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ListApplications is not implemented"))
}

func (UnimplementedStackServiceHandler) CreateApplication(context.Context, *connect.Request[v1.CreateApplicationRequest]) (*connect.Response[v1.Application], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.CreateApplication is not implemented"))
}

func (UnimplementedStackServiceHandler) DeleteApplication(context.Context, *connect.Request[v1.DeleteApplicationRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.DeleteApplication is not implemented"))
}

func (UnimplementedStackServiceHandler) UpdateApplication(context.Context, *connect.Request[v1.UpdateApplicationRequest]) (*connect.Response[v1.Application], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.UpdateApplication is not implemented"))
}

func (UnimplementedStackServiceHandler) AddApplicationUnit(context.Context, *connect.Request[v1.AddApplicationUnitRequest]) (*connect.Response[v1.Application], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.AddApplicationUnit is not implemented"))
}

func (UnimplementedStackServiceHandler) ExposeApplication(context.Context, *connect.Request[v1.ExposeApplicationRequest]) (*connect.Response[v1.Application], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ExposeApplication is not implemented"))
}

func (UnimplementedStackServiceHandler) ListIntegrations(context.Context, *connect.Request[v1.ListIntegrationsRequest]) (*connect.Response[v1.ListIntegrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ListIntegrations is not implemented"))
}

func (UnimplementedStackServiceHandler) CreateIntegration(context.Context, *connect.Request[v1.CreateIntegrationRequest]) (*connect.Response[v1.Integration], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.CreateIntegration is not implemented"))
}

func (UnimplementedStackServiceHandler) DeleteIntegration(context.Context, *connect.Request[v1.DeleteIntegrationRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.DeleteIntegration is not implemented"))
}

func (UnimplementedStackServiceHandler) ListActions(context.Context, *connect.Request[v1.ListActionsRequest]) (*connect.Response[v1.ListActionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.ListActions is not implemented"))
}

func (UnimplementedStackServiceHandler) RunAction(context.Context, *connect.Request[v1.RunActionRequest]) (*connect.Response[v1.Action], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("openhdc.stack.v1.StackService.RunAction is not implemented"))
}
