package core

import (
	"github.com/google/wire"

	"github.com/otterscale/otterscale/internal/core/application/chart"
	"github.com/otterscale/otterscale/internal/core/application/cluster"
	"github.com/otterscale/otterscale/internal/core/application/config"
	"github.com/otterscale/otterscale/internal/core/application/persistent"
	"github.com/otterscale/otterscale/internal/core/application/release"
	"github.com/otterscale/otterscale/internal/core/application/service"
	"github.com/otterscale/otterscale/internal/core/application/workload"
	"github.com/otterscale/otterscale/internal/core/bootstrap"
	"github.com/otterscale/otterscale/internal/core/configuration"
	"github.com/otterscale/otterscale/internal/core/configuration/bist"
	"github.com/otterscale/otterscale/internal/core/environment"
	"github.com/otterscale/otterscale/internal/core/facility"
	"github.com/otterscale/otterscale/internal/core/facility/action"
	"github.com/otterscale/otterscale/internal/core/facility/charm"
	"github.com/otterscale/otterscale/internal/core/instance/cdi"
	"github.com/otterscale/otterscale/internal/core/instance/vm"
	"github.com/otterscale/otterscale/internal/core/instance/vmi"
	"github.com/otterscale/otterscale/internal/core/instance/vnc"
	"github.com/otterscale/otterscale/internal/core/machine"
	"github.com/otterscale/otterscale/internal/core/machine/purge"
	"github.com/otterscale/otterscale/internal/core/machine/tag"
	"github.com/otterscale/otterscale/internal/core/model"
	"github.com/otterscale/otterscale/internal/core/network"
	"github.com/otterscale/otterscale/internal/core/orchestrator"
	"github.com/otterscale/otterscale/internal/core/orchestrator/extension"
	"github.com/otterscale/otterscale/internal/core/orchestrator/gpu"
	"github.com/otterscale/otterscale/internal/core/orchestrator/standalone"
	"github.com/otterscale/otterscale/internal/core/scope"
	"github.com/otterscale/otterscale/internal/core/storage"
	"github.com/otterscale/otterscale/internal/core/storage/block"
	"github.com/otterscale/otterscale/internal/core/storage/file"
	"github.com/otterscale/otterscale/internal/core/storage/object"
	"github.com/otterscale/otterscale/internal/core/storage/smb"
)

var ProviderSet = wire.NewSet(
	chart.NewUseCase,
	cluster.NewUseCase,
	config.NewUseCase,
	persistent.NewUseCase,
	release.NewUseCase,
	service.NewUseCase,
	workload.NewUseCase,
	bootstrap.NewUseCase,
	configuration.NewUseCase,
	bist.NewUseCase,
	environment.NewUseCase,
	facility.NewUseCase,
	action.NewUseCase,
	charm.NewUseCase,
	cdi.NewUseCase,
	vm.NewUseCase,
	vmi.NewUseCase,
	vnc.NewUseCase,
	machine.NewUseCase,
	purge.NewUseCase,
	tag.NewUseCase,
	model.NewUseCase,
	network.NewUseCase,
	orchestrator.NewUseCase,
	extension.NewUseCase,
	gpu.NewUseCase,
	standalone.NewUseCase,
	scope.NewUseCase,
	storage.NewUseCase,
	block.NewUseCase,
	file.NewUseCase,
	object.NewUseCase,
	smb.NewUseCase,
)
