package providers

import (
	"github.com/google/wire"

	"github.com/otterscale/otterscale/internal/providers/ceph"
	"github.com/otterscale/otterscale/internal/providers/helm"
	"github.com/otterscale/otterscale/internal/providers/juju"
	"github.com/otterscale/otterscale/internal/providers/kubernetes"
	"github.com/otterscale/otterscale/internal/providers/kubernetessigs"
	"github.com/otterscale/otterscale/internal/providers/kubevirt"
	"github.com/otterscale/otterscale/internal/providers/maas"
	"github.com/otterscale/otterscale/internal/providers/registry"
	"github.com/otterscale/otterscale/internal/providers/samba"
	"github.com/otterscale/otterscale/internal/providers/vault"
)

var ProviderSet = wire.NewSet(
	ceph.New,
	ceph.NewBucketRepo,
	ceph.NewImageRepo,
	ceph.NewImageSnapshotRepo,
	ceph.NewNodeRepo,
	ceph.NewPoolRepo,
	ceph.NewSubvolumeGroupRepo,
	ceph.NewSubvolumeRepo,
	ceph.NewSubvolumeSnapshotRepo,
	ceph.NewUserRepo,
	ceph.NewVolumeRepo,
	helm.New,
	helm.NewChartRepo,
	helm.NewReleaseRepo,
	juju.New,
	juju.NewActionRepo,
	juju.NewCharmRepo,
	juju.NewFacilityRepo,
	juju.NewMachineManagerRepo,
	juju.NewOrchestratorRepo,
	juju.NewRelationRepo,
	juju.NewScopeConfigRepo,
	juju.NewScopeRepo,
	kubernetes.New,
	kubernetes.NewConfigMapRepo,
	kubernetes.NewCustomResourceDefinitionRepo,
	kubernetes.NewDaemonSetRepo,
	kubernetes.NewDeploymentRepo,
	kubernetes.NewDiscoveryRepo,
	kubernetes.NewJobRepo,
	kubernetes.NewNamespaceRepo,
	kubernetes.NewNodeRepo,
	kubernetes.NewPersistentVolumeClaimRepo,
	kubernetes.NewPodRepo,
	kubernetes.NewResourceRepo,
	kubernetes.NewSecretRepo,
	kubernetes.NewServiceRepo,
	kubernetes.NewStatefulSetRepo,
	kubernetes.NewStorageClassRepo,
	kubernetessigs.New,
	kubernetessigs.NewGatewayRepo,
	kubernetessigs.NewHTTPRouteRepo,
	kubernetessigs.NewInferencePoolRepo,
	kubevirt.New,
	kubevirt.NewDataVolumeRepo,
	kubevirt.NewVirtualMachineCloneRepo,
	kubevirt.NewVirtualMachineInstanceMigrationRepo,
	kubevirt.NewVirtualMachineInstanceRepo,
	kubevirt.NewVirtualMachineInstanceTypeRepo,
	kubevirt.NewVirtualMachineRepo,
	kubevirt.NewVirtualMachineRestoreRepo,
	kubevirt.NewVirtualMachineSnapshotRepo,
	kubevirt.NewVNCRepo,
	maas.New,
	maas.NewBootResourceRepo,
	maas.NewBootSourceRepo,
	maas.NewBootSourceSelectionRepo,
	maas.NewEventRepo,
	maas.NewFabricRepo,
	maas.NewIPRangeRepo,
	maas.NewMachineRepo,
	maas.NewNodeDeviceRepo,
	maas.NewPackageRepositoryRepo,
	maas.NewProvisionerRepo,
	maas.NewSSHKeyRepo,
	maas.NewSubnetRepo,
	maas.NewTagRepo,
	maas.NewVLANRepo,
	registry.New,
	registry.NewManifestRepo,
	registry.NewRepositoryRepo,
	samba.New,
	samba.NewSMBCommonConfigRepo,
	samba.NewSMBShareRepo,
	samba.NewSMBSecurityConfigRepo,
	vault.New,
	vault.NewSecretRepo,
	vault.NewKubeConfigRepo,
)
