// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/configuration/v1/configuration.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Configuration struct {
	state                          protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_NtpServer           *Configuration_NTPServer            `protobuf:"bytes,1,opt,name=ntp_server,json=ntpServer"`
	xxx_hidden_PackageRepositories *[]*Configuration_PackageRepository `protobuf:"bytes,2,rep,name=package_repositories,json=packageRepositories"`
	xxx_hidden_BootImages          *[]*Configuration_BootImage         `protobuf:"bytes,3,rep,name=boot_images,json=bootImages"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration) GetNtpServer() *Configuration_NTPServer {
	if x != nil {
		return x.xxx_hidden_NtpServer
	}
	return nil
}

func (x *Configuration) GetPackageRepositories() []*Configuration_PackageRepository {
	if x != nil {
		if x.xxx_hidden_PackageRepositories != nil {
			return *x.xxx_hidden_PackageRepositories
		}
	}
	return nil
}

func (x *Configuration) GetBootImages() []*Configuration_BootImage {
	if x != nil {
		if x.xxx_hidden_BootImages != nil {
			return *x.xxx_hidden_BootImages
		}
	}
	return nil
}

func (x *Configuration) SetNtpServer(v *Configuration_NTPServer) {
	x.xxx_hidden_NtpServer = v
}

func (x *Configuration) SetPackageRepositories(v []*Configuration_PackageRepository) {
	x.xxx_hidden_PackageRepositories = &v
}

func (x *Configuration) SetBootImages(v []*Configuration_BootImage) {
	x.xxx_hidden_BootImages = &v
}

func (x *Configuration) HasNtpServer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NtpServer != nil
}

func (x *Configuration) ClearNtpServer() {
	x.xxx_hidden_NtpServer = nil
}

type Configuration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NtpServer           *Configuration_NTPServer
	PackageRepositories []*Configuration_PackageRepository
	BootImages          []*Configuration_BootImage
}

func (b0 Configuration_builder) Build() *Configuration {
	m0 := &Configuration{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NtpServer = b.NtpServer
	x.xxx_hidden_PackageRepositories = &b.PackageRepositories
	x.xxx_hidden_BootImages = &b.BootImages
	return m0
}

type GetConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetConfigurationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetConfigurationRequest_builder) Build() *GetConfigurationRequest {
	m0 := &GetConfigurationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type UpdateNTPServerRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Addresses []string               `protobuf:"bytes,1,rep,name=addresses"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateNTPServerRequest) Reset() {
	*x = UpdateNTPServerRequest{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNTPServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNTPServerRequest) ProtoMessage() {}

func (x *UpdateNTPServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateNTPServerRequest) GetAddresses() []string {
	if x != nil {
		return x.xxx_hidden_Addresses
	}
	return nil
}

func (x *UpdateNTPServerRequest) SetAddresses(v []string) {
	x.xxx_hidden_Addresses = v
}

type UpdateNTPServerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Addresses []string
}

func (b0 UpdateNTPServerRequest_builder) Build() *UpdateNTPServerRequest {
	m0 := &UpdateNTPServerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Addresses = b.Addresses
	return m0
}

type UpdatePackageRepositoryRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Url         *string                `protobuf:"bytes,2,opt,name=url"`
	xxx_hidden_SkipJuju    bool                   `protobuf:"varint,3,opt,name=skip_juju,json=skipJuju"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdatePackageRepositoryRequest) Reset() {
	*x = UpdatePackageRepositoryRequest{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePackageRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePackageRepositoryRequest) ProtoMessage() {}

func (x *UpdatePackageRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdatePackageRepositoryRequest) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *UpdatePackageRepositoryRequest) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *UpdatePackageRepositoryRequest) GetSkipJuju() bool {
	if x != nil {
		return x.xxx_hidden_SkipJuju
	}
	return false
}

func (x *UpdatePackageRepositoryRequest) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *UpdatePackageRepositoryRequest) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *UpdatePackageRepositoryRequest) SetSkipJuju(v bool) {
	x.xxx_hidden_SkipJuju = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *UpdatePackageRepositoryRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdatePackageRepositoryRequest) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdatePackageRepositoryRequest) HasSkipJuju() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdatePackageRepositoryRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *UpdatePackageRepositoryRequest) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Url = nil
}

func (x *UpdatePackageRepositoryRequest) ClearSkipJuju() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_SkipJuju = false
}

type UpdatePackageRepositoryRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       *int64
	Url      *string
	SkipJuju *bool
}

func (b0 UpdatePackageRepositoryRequest_builder) Build() *UpdatePackageRepositoryRequest {
	m0 := &UpdatePackageRepositoryRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Url = b.Url
	}
	if b.SkipJuju != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_SkipJuju = *b.SkipJuju
	}
	return m0
}

type CreateBootImageRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DistroSeries  *string                `protobuf:"bytes,1,opt,name=distro_series,json=distroSeries"`
	xxx_hidden_Architectures []string               `protobuf:"bytes,2,rep,name=architectures"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateBootImageRequest) Reset() {
	*x = CreateBootImageRequest{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBootImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBootImageRequest) ProtoMessage() {}

func (x *CreateBootImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateBootImageRequest) GetDistroSeries() string {
	if x != nil {
		if x.xxx_hidden_DistroSeries != nil {
			return *x.xxx_hidden_DistroSeries
		}
		return ""
	}
	return ""
}

func (x *CreateBootImageRequest) GetArchitectures() []string {
	if x != nil {
		return x.xxx_hidden_Architectures
	}
	return nil
}

func (x *CreateBootImageRequest) SetDistroSeries(v string) {
	x.xxx_hidden_DistroSeries = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateBootImageRequest) SetArchitectures(v []string) {
	x.xxx_hidden_Architectures = v
}

func (x *CreateBootImageRequest) HasDistroSeries() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateBootImageRequest) ClearDistroSeries() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DistroSeries = nil
}

type CreateBootImageRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DistroSeries  *string
	Architectures []string
}

func (b0 CreateBootImageRequest_builder) Build() *CreateBootImageRequest {
	m0 := &CreateBootImageRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DistroSeries != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_DistroSeries = b.DistroSeries
	}
	x.xxx_hidden_Architectures = b.Architectures
	return m0
}

type SetDefaultBootImageRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DistroSeries *string                `protobuf:"bytes,1,opt,name=distro_series,json=distroSeries"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SetDefaultBootImageRequest) Reset() {
	*x = SetDefaultBootImageRequest{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultBootImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultBootImageRequest) ProtoMessage() {}

func (x *SetDefaultBootImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetDefaultBootImageRequest) GetDistroSeries() string {
	if x != nil {
		if x.xxx_hidden_DistroSeries != nil {
			return *x.xxx_hidden_DistroSeries
		}
		return ""
	}
	return ""
}

func (x *SetDefaultBootImageRequest) SetDistroSeries(v string) {
	x.xxx_hidden_DistroSeries = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SetDefaultBootImageRequest) HasDistroSeries() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetDefaultBootImageRequest) ClearDistroSeries() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DistroSeries = nil
}

type SetDefaultBootImageRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DistroSeries *string
}

func (b0 SetDefaultBootImageRequest_builder) Build() *SetDefaultBootImageRequest {
	m0 := &SetDefaultBootImageRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DistroSeries != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_DistroSeries = b.DistroSeries
	}
	return m0
}

type ImportBootImagesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportBootImagesRequest) Reset() {
	*x = ImportBootImagesRequest{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportBootImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportBootImagesRequest) ProtoMessage() {}

func (x *ImportBootImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ImportBootImagesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ImportBootImagesRequest_builder) Build() *ImportBootImagesRequest {
	m0 := &ImportBootImagesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type IsImportingBootImagesRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsImportingBootImagesRequest) Reset() {
	*x = IsImportingBootImagesRequest{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsImportingBootImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsImportingBootImagesRequest) ProtoMessage() {}

func (x *IsImportingBootImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type IsImportingBootImagesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 IsImportingBootImagesRequest_builder) Build() *IsImportingBootImagesRequest {
	m0 := &IsImportingBootImagesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type IsImportingBootImagesResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Importing   bool                   `protobuf:"varint,1,opt,name=importing"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IsImportingBootImagesResponse) Reset() {
	*x = IsImportingBootImagesResponse{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsImportingBootImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsImportingBootImagesResponse) ProtoMessage() {}

func (x *IsImportingBootImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IsImportingBootImagesResponse) GetImporting() bool {
	if x != nil {
		return x.xxx_hidden_Importing
	}
	return false
}

func (x *IsImportingBootImagesResponse) SetImporting(v bool) {
	x.xxx_hidden_Importing = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *IsImportingBootImagesResponse) HasImporting() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *IsImportingBootImagesResponse) ClearImporting() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Importing = false
}

type IsImportingBootImagesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Importing *bool
}

func (b0 IsImportingBootImagesResponse_builder) Build() *IsImportingBootImagesResponse {
	m0 := &IsImportingBootImagesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Importing != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Importing = *b.Importing
	}
	return m0
}

type ListBootImageSelectionsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBootImageSelectionsRequest) Reset() {
	*x = ListBootImageSelectionsRequest{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBootImageSelectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBootImageSelectionsRequest) ProtoMessage() {}

func (x *ListBootImageSelectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListBootImageSelectionsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListBootImageSelectionsRequest_builder) Build() *ListBootImageSelectionsRequest {
	m0 := &ListBootImageSelectionsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListBootImageSelectionsResponse struct {
	state                          protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_BootImageSelections *[]*Configuration_BootImageSelection `protobuf:"bytes,1,rep,name=boot_image_selections,json=bootImageSelections"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ListBootImageSelectionsResponse) Reset() {
	*x = ListBootImageSelectionsResponse{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBootImageSelectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBootImageSelectionsResponse) ProtoMessage() {}

func (x *ListBootImageSelectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListBootImageSelectionsResponse) GetBootImageSelections() []*Configuration_BootImageSelection {
	if x != nil {
		if x.xxx_hidden_BootImageSelections != nil {
			return *x.xxx_hidden_BootImageSelections
		}
	}
	return nil
}

func (x *ListBootImageSelectionsResponse) SetBootImageSelections(v []*Configuration_BootImageSelection) {
	x.xxx_hidden_BootImageSelections = &v
}

type ListBootImageSelectionsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BootImageSelections []*Configuration_BootImageSelection
}

func (b0 ListBootImageSelectionsResponse_builder) Build() *ListBootImageSelectionsResponse {
	m0 := &ListBootImageSelectionsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BootImageSelections = &b.BootImageSelections
	return m0
}

type Configuration_NTPServer struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Addresses []string               `protobuf:"bytes,1,rep,name=addresses"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Configuration_NTPServer) Reset() {
	*x = Configuration_NTPServer{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_NTPServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_NTPServer) ProtoMessage() {}

func (x *Configuration_NTPServer) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_NTPServer) GetAddresses() []string {
	if x != nil {
		return x.xxx_hidden_Addresses
	}
	return nil
}

func (x *Configuration_NTPServer) SetAddresses(v []string) {
	x.xxx_hidden_Addresses = v
}

type Configuration_NTPServer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Addresses []string
}

func (b0 Configuration_NTPServer_builder) Build() *Configuration_NTPServer {
	m0 := &Configuration_NTPServer{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Addresses = b.Addresses
	return m0
}

type Configuration_PackageRepository struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Url         *string                `protobuf:"bytes,3,opt,name=url"`
	xxx_hidden_Enabled     bool                   `protobuf:"varint,4,opt,name=enabled"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Configuration_PackageRepository) Reset() {
	*x = Configuration_PackageRepository{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_PackageRepository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_PackageRepository) ProtoMessage() {}

func (x *Configuration_PackageRepository) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_PackageRepository) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Configuration_PackageRepository) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Configuration_PackageRepository) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *Configuration_PackageRepository) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *Configuration_PackageRepository) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Configuration_PackageRepository) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Configuration_PackageRepository) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Configuration_PackageRepository) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Configuration_PackageRepository) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_PackageRepository) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Configuration_PackageRepository) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Configuration_PackageRepository) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Configuration_PackageRepository) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Configuration_PackageRepository) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *Configuration_PackageRepository) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Url = nil
}

func (x *Configuration_PackageRepository) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Enabled = false
}

type Configuration_PackageRepository_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *int64
	Name    *string
	Url     *string
	Enabled *bool
}

func (b0 Configuration_PackageRepository_builder) Build() *Configuration_PackageRepository {
	m0 := &Configuration_PackageRepository{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Url = b.Url
	}
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	return m0
}

type Configuration_BootImageSelection struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DistroSeries  *string                `protobuf:"bytes,1,opt,name=distro_series,json=distroSeries"`
	xxx_hidden_Name          *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Architectures []string               `protobuf:"bytes,3,rep,name=architectures"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Configuration_BootImageSelection) Reset() {
	*x = Configuration_BootImageSelection{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_BootImageSelection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_BootImageSelection) ProtoMessage() {}

func (x *Configuration_BootImageSelection) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_BootImageSelection) GetDistroSeries() string {
	if x != nil {
		if x.xxx_hidden_DistroSeries != nil {
			return *x.xxx_hidden_DistroSeries
		}
		return ""
	}
	return ""
}

func (x *Configuration_BootImageSelection) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Configuration_BootImageSelection) GetArchitectures() []string {
	if x != nil {
		return x.xxx_hidden_Architectures
	}
	return nil
}

func (x *Configuration_BootImageSelection) SetDistroSeries(v string) {
	x.xxx_hidden_DistroSeries = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Configuration_BootImageSelection) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Configuration_BootImageSelection) SetArchitectures(v []string) {
	x.xxx_hidden_Architectures = v
}

func (x *Configuration_BootImageSelection) HasDistroSeries() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_BootImageSelection) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Configuration_BootImageSelection) ClearDistroSeries() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DistroSeries = nil
}

func (x *Configuration_BootImageSelection) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

type Configuration_BootImageSelection_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DistroSeries  *string
	Name          *string
	Architectures []string
}

func (b0 Configuration_BootImageSelection_builder) Build() *Configuration_BootImageSelection {
	m0 := &Configuration_BootImageSelection{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DistroSeries != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_DistroSeries = b.DistroSeries
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Architectures = b.Architectures
	return m0
}

type Configuration_BootImage struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source                *string                `protobuf:"bytes,1,opt,name=source"`
	xxx_hidden_DistroSeries          *string                `protobuf:"bytes,2,opt,name=distro_series,json=distroSeries"`
	xxx_hidden_Name                  *string                `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_ArchitectureStatusMap map[string]string      `protobuf:"bytes,5,rep,name=architecture_status_map,json=architectureStatusMap" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Default               bool                   `protobuf:"varint,11,opt,name=default"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *Configuration_BootImage) Reset() {
	*x = Configuration_BootImage{}
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_BootImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_BootImage) ProtoMessage() {}

func (x *Configuration_BootImage) ProtoReflect() protoreflect.Message {
	mi := &file_api_configuration_v1_configuration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration_BootImage) GetSource() string {
	if x != nil {
		if x.xxx_hidden_Source != nil {
			return *x.xxx_hidden_Source
		}
		return ""
	}
	return ""
}

func (x *Configuration_BootImage) GetDistroSeries() string {
	if x != nil {
		if x.xxx_hidden_DistroSeries != nil {
			return *x.xxx_hidden_DistroSeries
		}
		return ""
	}
	return ""
}

func (x *Configuration_BootImage) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Configuration_BootImage) GetArchitectureStatusMap() map[string]string {
	if x != nil {
		return x.xxx_hidden_ArchitectureStatusMap
	}
	return nil
}

func (x *Configuration_BootImage) GetDefault() bool {
	if x != nil {
		return x.xxx_hidden_Default
	}
	return false
}

func (x *Configuration_BootImage) SetSource(v string) {
	x.xxx_hidden_Source = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Configuration_BootImage) SetDistroSeries(v string) {
	x.xxx_hidden_DistroSeries = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Configuration_BootImage) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Configuration_BootImage) SetArchitectureStatusMap(v map[string]string) {
	x.xxx_hidden_ArchitectureStatusMap = v
}

func (x *Configuration_BootImage) SetDefault(v bool) {
	x.xxx_hidden_Default = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Configuration_BootImage) HasSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Configuration_BootImage) HasDistroSeries() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Configuration_BootImage) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Configuration_BootImage) HasDefault() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Configuration_BootImage) ClearSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Source = nil
}

func (x *Configuration_BootImage) ClearDistroSeries() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DistroSeries = nil
}

func (x *Configuration_BootImage) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *Configuration_BootImage) ClearDefault() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Default = false
}

type Configuration_BootImage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Source                *string
	DistroSeries          *string
	Name                  *string
	ArchitectureStatusMap map[string]string
	Default               *bool
}

func (b0 Configuration_BootImage_builder) Build() *Configuration_BootImage {
	m0 := &Configuration_BootImage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Source != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Source = b.Source
	}
	if b.DistroSeries != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_DistroSeries = b.DistroSeries
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_ArchitectureStatusMap = b.ArchitectureStatusMap
	if b.Default != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Default = *b.Default
	}
	return m0
}

var File_api_configuration_v1_configuration_proto protoreflect.FileDescriptor

const file_api_configuration_v1_configuration_proto_rawDesc = "" +
	"\n" +
	"(api/configuration/v1/configuration.proto\x12\x1botterscale.configuration.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xfe\x06\n" +
	"\rConfiguration\x12S\n" +
	"\n" +
	"ntp_server\x18\x01 \x01(\v24.otterscale.configuration.v1.Configuration.NTPServerR\tntpServer\x12o\n" +
	"\x14package_repositories\x18\x02 \x03(\v2<.otterscale.configuration.v1.Configuration.PackageRepositoryR\x13packageRepositories\x12U\n" +
	"\vboot_images\x18\x03 \x03(\v24.otterscale.configuration.v1.Configuration.BootImageR\n" +
	"bootImages\x1a)\n" +
	"\tNTPServer\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x1ac\n" +
	"\x11PackageRepository\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x1as\n" +
	"\x12BootImageSelection\x12#\n" +
	"\rdistro_series\x18\x01 \x01(\tR\fdistroSeries\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\rarchitectures\x18\x03 \x03(\tR\rarchitectures\x1a\xca\x02\n" +
	"\tBootImage\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12#\n" +
	"\rdistro_series\x18\x02 \x01(\tR\fdistroSeries\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x87\x01\n" +
	"\x17architecture_status_map\x18\x05 \x03(\v2O.otterscale.configuration.v1.Configuration.BootImage.ArchitectureStatusMapEntryR\x15architectureStatusMap\x12\x18\n" +
	"\adefault\x18\v \x01(\bR\adefault\x1aH\n" +
	"\x1aArchitectureStatusMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x19\n" +
	"\x17GetConfigurationRequest\"6\n" +
	"\x16UpdateNTPServerRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"_\n" +
	"\x1eUpdatePackageRepositoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1b\n" +
	"\tskip_juju\x18\x03 \x01(\bR\bskipJuju\"c\n" +
	"\x16CreateBootImageRequest\x12#\n" +
	"\rdistro_series\x18\x01 \x01(\tR\fdistroSeries\x12$\n" +
	"\rarchitectures\x18\x02 \x03(\tR\rarchitectures\"A\n" +
	"\x1aSetDefaultBootImageRequest\x12#\n" +
	"\rdistro_series\x18\x01 \x01(\tR\fdistroSeries\"\x19\n" +
	"\x17ImportBootImagesRequest\"\x1e\n" +
	"\x1cIsImportingBootImagesRequest\"=\n" +
	"\x1dIsImportingBootImagesResponse\x12\x1c\n" +
	"\timporting\x18\x01 \x01(\bR\timporting\" \n" +
	"\x1eListBootImageSelectionsRequest\"\x94\x01\n" +
	"\x1fListBootImageSelectionsResponse\x12q\n" +
	"\x15boot_image_selections\x18\x01 \x03(\v2=.otterscale.configuration.v1.Configuration.BootImageSelectionR\x13bootImageSelections2\x91\b\n" +
	"\x14ConfigurationService\x12t\n" +
	"\x10GetConfiguration\x124.otterscale.configuration.v1.GetConfigurationRequest\x1a*.otterscale.configuration.v1.Configuration\x12|\n" +
	"\x0fUpdateNTPServer\x123.otterscale.configuration.v1.UpdateNTPServerRequest\x1a4.otterscale.configuration.v1.Configuration.NTPServer\x12\x94\x01\n" +
	"\x17UpdatePackageRepository\x12;.otterscale.configuration.v1.UpdatePackageRepositoryRequest\x1a<.otterscale.configuration.v1.Configuration.PackageRepository\x12|\n" +
	"\x0fCreateBootImage\x123.otterscale.configuration.v1.CreateBootImageRequest\x1a4.otterscale.configuration.v1.Configuration.BootImage\x12f\n" +
	"\x13SetDefaultBootImage\x127.otterscale.configuration.v1.SetDefaultBootImageRequest\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\x10ImportBootImages\x124.otterscale.configuration.v1.ImportBootImagesRequest\x1a\x16.google.protobuf.Empty\x12\x8e\x01\n" +
	"\x15IsImportingBootImages\x129.otterscale.configuration.v1.IsImportingBootImagesRequest\x1a:.otterscale.configuration.v1.IsImportingBootImagesResponse\x12\x94\x01\n" +
	"\x17ListBootImageSelections\x12;.otterscale.configuration.v1.ListBootImageSelectionsRequest\x1a<.otterscale.configuration.v1.ListBootImageSelectionsResponseB:Z8github.com/otterscale/otterscale/api/configuration/v1;pbb\beditionsp\xe8\a"

var file_api_configuration_v1_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_configuration_v1_configuration_proto_goTypes = []any{
	(*Configuration)(nil),                    // 0: otterscale.configuration.v1.Configuration
	(*GetConfigurationRequest)(nil),          // 1: otterscale.configuration.v1.GetConfigurationRequest
	(*UpdateNTPServerRequest)(nil),           // 2: otterscale.configuration.v1.UpdateNTPServerRequest
	(*UpdatePackageRepositoryRequest)(nil),   // 3: otterscale.configuration.v1.UpdatePackageRepositoryRequest
	(*CreateBootImageRequest)(nil),           // 4: otterscale.configuration.v1.CreateBootImageRequest
	(*SetDefaultBootImageRequest)(nil),       // 5: otterscale.configuration.v1.SetDefaultBootImageRequest
	(*ImportBootImagesRequest)(nil),          // 6: otterscale.configuration.v1.ImportBootImagesRequest
	(*IsImportingBootImagesRequest)(nil),     // 7: otterscale.configuration.v1.IsImportingBootImagesRequest
	(*IsImportingBootImagesResponse)(nil),    // 8: otterscale.configuration.v1.IsImportingBootImagesResponse
	(*ListBootImageSelectionsRequest)(nil),   // 9: otterscale.configuration.v1.ListBootImageSelectionsRequest
	(*ListBootImageSelectionsResponse)(nil),  // 10: otterscale.configuration.v1.ListBootImageSelectionsResponse
	(*Configuration_NTPServer)(nil),          // 11: otterscale.configuration.v1.Configuration.NTPServer
	(*Configuration_PackageRepository)(nil),  // 12: otterscale.configuration.v1.Configuration.PackageRepository
	(*Configuration_BootImageSelection)(nil), // 13: otterscale.configuration.v1.Configuration.BootImageSelection
	(*Configuration_BootImage)(nil),          // 14: otterscale.configuration.v1.Configuration.BootImage
	nil,                                      // 15: otterscale.configuration.v1.Configuration.BootImage.ArchitectureStatusMapEntry
	(*emptypb.Empty)(nil),                    // 16: google.protobuf.Empty
}
var file_api_configuration_v1_configuration_proto_depIdxs = []int32{
	11, // 0: otterscale.configuration.v1.Configuration.ntp_server:type_name -> otterscale.configuration.v1.Configuration.NTPServer
	12, // 1: otterscale.configuration.v1.Configuration.package_repositories:type_name -> otterscale.configuration.v1.Configuration.PackageRepository
	14, // 2: otterscale.configuration.v1.Configuration.boot_images:type_name -> otterscale.configuration.v1.Configuration.BootImage
	13, // 3: otterscale.configuration.v1.ListBootImageSelectionsResponse.boot_image_selections:type_name -> otterscale.configuration.v1.Configuration.BootImageSelection
	15, // 4: otterscale.configuration.v1.Configuration.BootImage.architecture_status_map:type_name -> otterscale.configuration.v1.Configuration.BootImage.ArchitectureStatusMapEntry
	1,  // 5: otterscale.configuration.v1.ConfigurationService.GetConfiguration:input_type -> otterscale.configuration.v1.GetConfigurationRequest
	2,  // 6: otterscale.configuration.v1.ConfigurationService.UpdateNTPServer:input_type -> otterscale.configuration.v1.UpdateNTPServerRequest
	3,  // 7: otterscale.configuration.v1.ConfigurationService.UpdatePackageRepository:input_type -> otterscale.configuration.v1.UpdatePackageRepositoryRequest
	4,  // 8: otterscale.configuration.v1.ConfigurationService.CreateBootImage:input_type -> otterscale.configuration.v1.CreateBootImageRequest
	5,  // 9: otterscale.configuration.v1.ConfigurationService.SetDefaultBootImage:input_type -> otterscale.configuration.v1.SetDefaultBootImageRequest
	6,  // 10: otterscale.configuration.v1.ConfigurationService.ImportBootImages:input_type -> otterscale.configuration.v1.ImportBootImagesRequest
	7,  // 11: otterscale.configuration.v1.ConfigurationService.IsImportingBootImages:input_type -> otterscale.configuration.v1.IsImportingBootImagesRequest
	9,  // 12: otterscale.configuration.v1.ConfigurationService.ListBootImageSelections:input_type -> otterscale.configuration.v1.ListBootImageSelectionsRequest
	0,  // 13: otterscale.configuration.v1.ConfigurationService.GetConfiguration:output_type -> otterscale.configuration.v1.Configuration
	11, // 14: otterscale.configuration.v1.ConfigurationService.UpdateNTPServer:output_type -> otterscale.configuration.v1.Configuration.NTPServer
	12, // 15: otterscale.configuration.v1.ConfigurationService.UpdatePackageRepository:output_type -> otterscale.configuration.v1.Configuration.PackageRepository
	14, // 16: otterscale.configuration.v1.ConfigurationService.CreateBootImage:output_type -> otterscale.configuration.v1.Configuration.BootImage
	16, // 17: otterscale.configuration.v1.ConfigurationService.SetDefaultBootImage:output_type -> google.protobuf.Empty
	16, // 18: otterscale.configuration.v1.ConfigurationService.ImportBootImages:output_type -> google.protobuf.Empty
	8,  // 19: otterscale.configuration.v1.ConfigurationService.IsImportingBootImages:output_type -> otterscale.configuration.v1.IsImportingBootImagesResponse
	10, // 20: otterscale.configuration.v1.ConfigurationService.ListBootImageSelections:output_type -> otterscale.configuration.v1.ListBootImageSelectionsResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_configuration_v1_configuration_proto_init() }
func file_api_configuration_v1_configuration_proto_init() {
	if File_api_configuration_v1_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_configuration_v1_configuration_proto_rawDesc), len(file_api_configuration_v1_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_configuration_v1_configuration_proto_goTypes,
		DependencyIndexes: file_api_configuration_v1_configuration_proto_depIdxs,
		MessageInfos:      file_api_configuration_v1_configuration_proto_msgTypes,
	}.Build()
	File_api_configuration_v1_configuration_proto = out.File
	file_api_configuration_v1_configuration_proto_goTypes = nil
	file_api_configuration_v1_configuration_proto_depIdxs = nil
}
