# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
    - name: Install Ceph development libraries
      run: |
        sudo apt update
        sudo apt install -y libcephfs-dev librbd-dev librados-dev
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
